/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "NSCopying.h"
#import <Foundation/NSObject.h>

@class UIColor;

__attribute__((visibility("hidden")))
@interface _UIGroupTableViewCellBackgroundImageKey : NSObject <NSCopying> {
@private
	BOOL _opaque;
	CGSize _size;
	UIColor* _backgroundColor;
	UIColor* _borderColor;
	UIColor* _fillColor;
	float _leftPhase;
	float _rightPhase;
	int _sectionLocation;
}
@property(assign, nonatomic) BOOL opaque;
@property(assign, nonatomic) CGSize size;
@property(retain, nonatomic) UIColor* backgroundColor;
@property(retain, nonatomic) UIColor* borderColor;
@property(retain, nonatomic) UIColor* fillColor;
@property(assign, nonatomic) float leftPhase;
@property(assign, nonatomic) float rightPhase;
@property(assign, nonatomic) int sectionLocation;
-(void)dealloc;
-(BOOL)isEqual:(id)equal;
-(unsigned)hash;
-(id)copyWithZone:(NSZone*)zone;
-(id)description;
@end

