/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface _UIGroupItem : NSObject {
@private
	NSString* _title;
	float offset;
	int _rowCountBeforeGroup;
	int _childCount;
	unsigned _isRadioGroup : 1;
	unsigned _isLabelGroup : 1;
	unsigned _reserved : 30;
}
-(id)initWithTitle:(id)title childCount:(int)count rowCountBeforeGroup:(int)group isRadioGroup:(BOOL)group4;
-(void)dealloc;
-(int)childCount;
-(id)title;
-(int)rowCountBeforeGroup;
-(int)tableRowForRow:(int)row;
@end

