/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>

@class NSArray, UIImage;

__attribute__((visibility("hidden")))
@interface _UIImageViewExtendedStorage : NSObject {
@private
	BOOL _highlighted;
	UIImage* _image;
	UIImage* _highlightedImage;
	NSArray* _animationImages;
	NSArray* _highlightedAnimationImages;
	double _animationDuration;
	int _animationRepeatCount;
	int _drawMode;
}
-(void)dealloc;
@end

