/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIThreePartButton.h"
#import "UIKit-Structs.h"

@class UILabel;

__attribute__((visibility("hidden")))
@interface _UILabeledPushButton : UIThreePartButton {
@private
	UILabel* _textLabel;
}
-(void)dealloc;
-(void)setLabel:(id)label;
-(void)setLabelFontSize:(float)size;
-(float)labelFontSize;
-(void)layoutSubviews;
-(void)setHighlighted:(BOOL)highlighted;
-(void)drawTitleAtPoint:(CGPoint)point width:(float)width;
@end

