/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UITableCell.h"

@class UIView;

__attribute__((visibility("hidden")))
@interface _UIPickerViewWrappingTableCell : UITableCell {
@private
	UIView* _wrappedView;
}
-(void)dealloc;
-(void)setWrappedView:(id)view;
-(id)wrappedView;
@end

