/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIImageView.h"


__attribute__((visibility("hidden")))
@interface _UIPrefTableCellPiece : UIImageView {
@private
	CGRect _originalFrame;
	UIView* _syncPiece;
}
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(CGRect)originalFrame;
-(void)setSyncPiece:(id)piece;
-(id)syncPiece;
@end

