/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>

@class NSArray, UIShadowView, NSTimer;

__attribute__((visibility("hidden")))
@interface _UITableReorderingSupport : NSObject {
@private
	NSArray* _reorderedCells;
	unsigned _reorderedRow;
	unsigned _emptySpaceRow;
	unsigned _lastVisibleRowLocation;
	unsigned _oldShowScrollerIndicators : 1;
	unsigned _delegateImplementsCanMoveRow : 1;
	unsigned _delegateImplementsMoveDestinationRow : 1;
	unsigned _bottomShadowNeedsToMove : 1;
	unsigned _reserved : 28;
	NSTimer* _autoscrollTimer;
	UIShadowView* _topShadowView;
	UIShadowView* _bottomShadowView;
}
@end

