/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface _UITableViewDeleteAnimationSupport : NSObject {
@private
	NSMutableArray* _cellsToDeleteAfterAnimation;
	int _deleteCount;
	unsigned _enabledStateBeforeDeleteAnimation : 1;
	unsigned _reserved : 30;
}
@end

