/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIControl.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface _UITableViewCellDeleteConfirmationControl : UIControl {
@private
	NSString* _title;
}
@property(readonly, assign, nonatomic) NSString* title;
@property(readonly, assign, nonatomic) CGSize size;
+(CGSize)defaultSizeForTitle:(id)title;
+(id)_backgroundImage;
+(id)_highlightedBackgroundImage;
-(id)initWithTitle:(id)title;
-(void)dealloc;
-(void)drawBackgroundInRect:(CGRect)rect;
-(void)drawRect:(CGRect)rect;
@end

