/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIView.h"

@class UITableView, UITableViewCell;

__attribute__((visibility("hidden")))
@interface _UITableViewSeparatorView : UIView {
@private
	UITableViewCell* _tableCell;
	UITableView* _table;
}
-(id)initWithTableCell:(id)tableCell;
-(id)initWithFrame:(CGRect)frame withTable:(id)table;
-(void)drawRect:(CGRect)rect;
@end

