/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <QuartzCore/CALayer.h>
#import "UIKit-Structs.h"


__attribute__((visibility("hidden")))
@interface _UIWindowLayer : CALayer {
}
-(id)init;
-(void)setPosition:(CGPoint)position;
-(CGPoint)position;
-(void)setAffineTransform:(CGAffineTransform)transform;
-(CGAffineTransform)affineTransform;
-(CGRect)frame;
@end

