/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface ABHelper : NSObject {
@private
	void* _ab;
	void* _me;
}
+(id)sharedHelper;
-(id)initHelper;
-(void)dealloc;
-(void*)me;
@end

