/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface AddressBookMatch : NSObject {
@private
	NSString* value;
	NSString* property;
	NSString* key;
	int identifier;
}
-(id)initWithValue:(id)value property:(id)property key:(id)key identifier:(int)identifier;
-(id)description;
-(void)dealloc;
@end

