/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>

@class NSData, NSString;

__attribute__((visibility("hidden")))
@interface CandWordString : NSObject {
@private
	NSString* _string;
	char* _UTF8String;
	NSData* _utf8Data;
}
-(id)initWithString:(id)string;
-(void)dealloc;
-(id)string;
-(const char*)UTF8String;
@end

