/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIScrollView.h"


__attribute__((visibility("hidden")))
@interface EmojiScrollView : UIScrollView {
@private
	double _delay;
	BOOL _canDragToScroll;
}
@property(assign) double delay;
-(id)initWithFrame:(CGRect)frame;
-(double)_touchDelayForScrollDetection;
-(void)setContentOffset:(CGPoint)offset;
-(void)_stopLookingForScrolling;
-(void)_lookForScrolling;
-(BOOL)touchesShouldBegin:(id)touches withEvent:(id)event inContentView:(id)contentView;
-(BOOL)touchesShouldCancelInContentView:(id)touches;
@end

