/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>


@interface Romakana : NSObject {
	BOOL _kanaMode;
}
+(id)oneKanaToRoma:(id)roma;
+(id)hiraganaString:(id)string withKanaMode:(BOOL)kanaMode;
+(id)hiraganaString:(id)string mappingArray:(id)array withKanaMode:(BOOL)kanaMode;
-(id)initWithKanaMode:(BOOL)kanaMode;
-(id)roma2hiragana:(id)hiragana stripIncompleteRomajiAtEnd:(BOOL)end;
-(id)roma2katakana:(id)katakana;
@end

