/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>


@interface UIAcceleration : NSObject {
@private
	double timestamp;
	double x;
	double y;
	double z;
}
@property(assign, nonatomic) double timestamp;
@property(assign, nonatomic) double x;
@property(assign, nonatomic) double y;
@property(assign, nonatomic) double z;
@end

