/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>

@protocol UIAccelerometerDelegate;

@interface UIAccelerometer : NSObject {
@private
	double _updateInterval;
	id<UIAccelerometerDelegate> _delegate;
	struct {
		unsigned style : 1;
		unsigned reserved : 31;
	} _accelerometerFlags;
}
@property(assign, nonatomic) double updateInterval;
@property(assign, nonatomic) id<UIAccelerometerDelegate> delegate;
+(id)sharedAccelerometer;
-(id)init;
-(void)_acceleratedInX:(double)x y:(double)y z:(double)z timestamp:(double)timestamp;
@end

