/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIActivityIndicatorView.h"
#import "UIKit-Structs.h"
#import "NSCoding.h"
#import "UIView.h"


@interface UIActivityIndicatorView : UIView <NSCoding> {
@private
	double _duration;
	BOOL _animating;
	int _activityIndicatorViewStyle;
	BOOL _hidesWhenStopped;
}
@property(assign, nonatomic) int activityIndicatorViewStyle;
@property(assign, nonatomic) BOOL hidesWhenStopped;
+(void)_loadResourcesForStyle:(int)style;
+(CGSize)defaultSizeForStyle:(int)style;
+(CGSize)size;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithActivityIndicatorStyle:(int)activityIndicatorStyle;
-(void)dealloc;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)startAnimating;
-(void)stopAnimating;
-(BOOL)isAnimating;
-(void)setAnimationDuration:(double)duration;
-(void)_didMoveFromWindow:(id)window toWindow:(id)window2;
-(void)setStyle:(int)style;
-(void)setAnimating:(BOOL)animating;
-(void)startAnimation;
-(void)stopAnimation;
@end

@interface UIActivityIndicatorView (UIKitAccessibilityInterfaceBuilderSupport)
-(BOOL)isElementAccessibilityExposedToInterfaceBuilder;
@end

