/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIView.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface UIAccentedKeyCapStringView : UIView {
@private
	BOOL m_selectedMode;
	int m_expansion;
	int m_orientation;
	float m_stringWidth;
	NSArray* m_caps;
}
-(void)dealloc;
-(void)setSelectedMode:(BOOL)mode;
-(void)setCaps:(id)caps;
-(void)setExpansion:(int)expansion;
-(void)setOrientation:(int)orientation;
-(void)setStringWidth:(float)width;
-(void)drawRect:(CGRect)rect;
@end

