/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UITextField.h"
#import "UIKit-Structs.h"

@class UIThreePartImageView;

__attribute__((visibility("hidden")))
@interface UIAlertSheetTextField : UITextField {
@private
	UIThreePartImageView* _sheetBackgroundView;
}
-(void)dealloc;
-(void)setBackgroundView:(id)view;
-(id)backgroundView;
@end

