/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import <Foundation/NSObject.h>
#import "UIAnimator.h"

@class NSMutableArray;

@interface UIAnimator : NSObject {
	NSMutableArray* _animations;
	double _lastUpdateTime;
	GSHeartbeatRef _lcdHeartbeat;
	GSHeartbeatRef _tvHeartbeat;
	int _lcdCount;
	int _tvCount;
}
+(id)sharedAnimator;
+(void)disableAnimation;
+(void)enableAnimation;
-(void)dealloc;
-(void)addAnimation:(id)animation withDuration:(double)duration start:(BOOL)start;
-(void)addAnimations:(id)animations withDuration:(double)duration start:(BOOL)start;
-(void)removeAnimationsForTarget:(id)target;
-(void)removeAnimationsForTarget:(id)target ofKind:(Class)kind;
-(void)startAnimation:(id)animation;
-(void)stopAnimation:(id)animation;
-(float)fractionForAnimation:(id)animation;
@end

@interface UIAnimator (Static)
-(void)_addAnimation:(id)animation withDuration:(double)duration start:(BOOL)start startTime:(double)time;
-(void)_startAnimation:(id)animation withStartTime:(double)startTime;
-(void)_advance:(BOOL)advance;
@end

