/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIAnimation.h"
#import <Foundation/NSObject.h>


@interface UIAnimation : NSObject {
	id _target;
	SEL _action;
	id _delegate;
	struct {
		unsigned curve : 4;
		unsigned tvOutput : 1;
		unsigned reserved : 27;
	} _animationFlags;
@private
	double _startTime;
	double _duration;
	int _state;
}
-(id)initWithTarget:(id)target;
-(void)stopAnimation;
-(id)target;
-(void)setDelegate:(id)delegate;
-(id)delegate;
-(void)setAction:(SEL)action;
-(SEL)action;
-(void)setAnimationCurve:(int)curve;
-(void)setProgress:(float)progress;
-(float)progressForFraction:(float)fraction;
-(void)dealloc;
@end

@interface UIAnimation (Internal)
-(int)state;
-(BOOL)tvOutput;
-(void)setDuration:(double)duration;
-(float)fractionForTime:(double)time;
-(void)markStart:(double)start;
-(void)markStop;
@end

