/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIView.h"

@class UIImage;

__attribute__((visibility("hidden")))
@interface UIAutocorrectImageView : UIView {
@private
	UIImage* m_image;
}
+(id)imageWithMaskingView:(id)maskingView maskingRect:(CGRect)rect;
-(id)initWithFrame:(CGRect)frame image:(id)image;
-(id)initWithFrame:(CGRect)frame string:(id)string font:(id)font;
-(void)dealloc;
-(void)drawRect:(CGRect)rect;
@end

