/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIView.h"

@class NSString, UIFont;

__attribute__((visibility("hidden")))
@interface UIAutocorrectTextView : UIView {
@private
	NSString* m_string;
	int m_type;
	int m_edgeType;
	UIFont* m_textFont;
	BOOL m_animating;
}
-(id)initWithFrame:(CGRect)frame string:(id)string type:(int)type edgeType:(int)type4;
-(void)dealloc;
-(void)setEdgeType:(int)type;
-(void)setAnimating:(BOOL)animating;
-(void)drawRect:(CGRect)rect;
-(BOOL)needsWebDocumentViewEventsDirectly;
@end

