/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>
#import "UIKit-Structs.h"

@class NSString, UIImage;

@interface UIBarItem : NSObject {
}
@property(assign, nonatomic, getter=isEnabled) BOOL enabled;
@property(copy, nonatomic) NSString* title;
@property(retain, nonatomic) UIImage* image;
@property(assign, nonatomic) UIEdgeInsets imageInsets;
@property(assign, nonatomic) int tag;
@end

