/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UILabel.h"


__attribute__((visibility("hidden")))
@interface UIButtonLabel : UILabel {
@private
	BOOL _reverseShadow;
}
-(void)setFont:(id)font;
-(void)setLineBreakMode:(int)mode;
-(void)setShadowOffset:(CGSize)offset;
-(CGSize)shadowOffset;
-(void)setReverseShadow:(BOOL)shadow;
@end

