/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "NSCopying.h"
#import <Foundation/NSObject.h>
#import "NSCoding.h"
#import "UIKit-Structs.h"

@class UIColor, NSString, UIImage;

__attribute__((visibility("hidden")))
@interface UIButtonContent : NSObject <NSCoding, NSCopying> {
@private
	NSString* title;
	UIImage* image;
	UIImage* background;
	UIColor* titleColor;
	UIColor* shadowColor;
}
@property(retain, nonatomic) NSString* title;
@property(retain, nonatomic) UIImage* image;
@property(retain, nonatomic) UIImage* background;
@property(retain, nonatomic) UIColor* titleColor;
@property(retain, nonatomic) UIColor* shadowColor;
@property(readonly, assign, nonatomic) BOOL isEmpty;
-(id)copyWithZone:(NSZone*)zone;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)dealloc;
-(id)description;
@end

