/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "NSCoding.h"
#import "UIButton.h"
#import "UIControl.h"

@class UIFont, NSString, UILabel, UIImage, UIImageView, UIColor;

@interface UIButton : UIControl <NSCoding> {
@private
	CFDictionaryRef _contentLookup;
	UIEdgeInsets _contentEdgeInsets;
	UIEdgeInsets _titleEdgeInsets;
	UIEdgeInsets _imageEdgeInsets;
	UIImageView* _backgroundView;
	UIImageView* _imageView;
	UILabel* _titleView;
	struct {
		unsigned reversesTitleShadowWhenHighlighted : 1;
		unsigned adjustsImageWhenHighlighted : 1;
		unsigned adjustsImageWhenDisabled : 1;
		unsigned autosizeToFit : 1;
		unsigned disabledDimsImage : 1;
		unsigned showsTouchWhenHighlighted : 1;
		unsigned buttonType : 8;
		unsigned shouldHandleScrollerMouseEvent : 1;
	} _buttonFlags;
}
@property(assign, nonatomic) UIEdgeInsets contentEdgeInsets;
@property(assign, nonatomic) UIEdgeInsets titleEdgeInsets;
@property(assign, nonatomic) BOOL reversesTitleShadowWhenHighlighted;
@property(assign, nonatomic) BOOL adjustsImageWhenHighlighted;
@property(assign, nonatomic) BOOL adjustsImageWhenDisabled;
@property(assign, nonatomic) UIEdgeInsets imageEdgeInsets;
@property(readonly, retain, nonatomic) UIImageView* imageView;
@property(readonly, retain, nonatomic) UILabel* titleLabel;
@property(readonly, retain, nonatomic) UIImage* currentBackgroundImage;
@property(readonly, retain, nonatomic) UIImage* currentImage;
@property(readonly, retain, nonatomic) UIColor* currentTitleShadowColor;
@property(readonly, retain, nonatomic) UIColor* currentTitleColor;
@property(readonly, retain, nonatomic) NSString* currentTitle;
@property(readonly, assign, nonatomic) int buttonType;
@property(assign, nonatomic) BOOL showsTouchWhenHighlighted;
+(id)_defaultContentForType:(int)type andState:(unsigned)state;
+(id)buttonWithType:(int)type;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithCoder:(id)coder;
-(void)_populateArchivedSubviews:(id)subviews;
-(void)encodeWithCoder:(id)coder;
-(void)dealloc;
-(void)setFrame:(CGRect)frame;
-(void)setBounds:(CGRect)bounds;
-(void)setSelected:(BOOL)selected;
-(void)setEnabled:(BOOL)enabled;
-(void)setHighlighted:(BOOL)highlighted;
-(void)setContentHorizontalAlignment:(int)alignment;
-(void)setTitle:(id)title forState:(unsigned)state;
-(void)setTitleColor:(id)color forState:(unsigned)state;
-(void)setTitleShadowColor:(id)color forState:(unsigned)state;
-(void)setImage:(id)image forState:(unsigned)state;
-(void)setBackgroundImage:(id)image forState:(unsigned)state;
-(id)titleForState:(unsigned)state;
-(id)titleColorForState:(unsigned)state;
-(id)titleShadowColorForState:(unsigned)state;
-(id)imageForState:(unsigned)state;
-(id)backgroundImageForState:(unsigned)state;
-(CGRect)backgroundRectForBounds:(CGRect)bounds;
-(CGRect)contentRectForBounds:(CGRect)bounds;
-(CGRect)titleRectForContentRect:(CGRect)contentRect;
-(CGRect)imageRectForContentRect:(CGRect)contentRect;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)layoutSubviews;
@end

@interface UIButton (SyntheticEvents)
-(id)_scriptingInfo;
@end

@interface UIButton (UIButtonContentLookup)
-(void)_setContent:(id)content forState:(unsigned)state;
-(void)_setImage:(id)image forStates:(unsigned)states;
-(void)_setBackground:(id)background forStates:(unsigned)states;
-(void)_setTitle:(id)title forStates:(unsigned)states;
-(void)_setTitleColor:(id)color forStates:(unsigned)states;
-(void)_setShadowColor:(id)color forStates:(unsigned)states;
-(id)_contentForState:(unsigned)state;
-(id)_archivableContent:(id*)content;
-(void)_takeContentFromArchivableContent:(id)archivableContent overrides:(id)overrides;
-(id)_imageForState:(unsigned)state usesImageForNormalState:(BOOL*)normalState;
-(id)_backgroundForState:(unsigned)state usesBackgroundForNormalState:(BOOL*)normalState;
-(id)_titleForState:(unsigned)state;
-(id)_titleColorForState:(unsigned)state;
-(id)_shadowColorForState:(unsigned)state;
@end

@interface UIButton (UIButtonPrivate)
@property(retain, nonatomic) UIColor* tintColor;
-(BOOL)_alwaysHandleScrollerMouseEvent;
-(void)_setShouldHandleScrollerMouseEvent:(BOOL)_set;
-(void)setAutosizesToFit:(BOOL)fit;
-(BOOL)autosizesToFit;
-(void)setDisabledDimsImage:(BOOL)image;
-(void)setShowPressFeedback:(BOOL)feedback;
-(CGPoint)pressFeedbackPosition;
-(void)setTitle:(id)title forStates:(unsigned)states;
-(void)setTitleColor:(id)color forStates:(unsigned)states;
-(void)setTitleShadowColor:(id)color forStates:(unsigned)states;
-(void)setImage:(id)image forStates:(unsigned)states;
-(void)setBackgroundImage:(id)image forStates:(unsigned)states;
-(id)_font;
-(void)_setFont:(id)font;
-(int)_lineBreakMode;
-(void)_setLineBreakMode:(int)mode;
-(CGSize)_titleShadowOffset;
-(void)_setTitleShadowOffset:(CGSize)offset;
@end

@interface UIButton (UIButtonInternal)
-(void)_setupBackgroundView;
-(void)_setupImageView;
-(void)_setupTitleView;
-(void)_setButtonType:(int)type;
-(void)_titleAttributesChanged;
@end

@interface UIButton (UIButtonDeprecated)
@property(assign, nonatomic) CGSize titleShadowOffset;
@property(assign, nonatomic) int lineBreakMode;
@property(retain, nonatomic) UIFont* font;
@end

@interface UIButton (UIKitAccessibilityInterfaceBuilderSupport)
-(BOOL)isAccessibilityElementByDefault;
-(unsigned long long)defaultAccessibilityTraits;
-(BOOL)isElementAccessibilityExposedToInterfaceBuilder;
@end

