/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIDeviceRGBColor.h"
#import "UIKit-Structs.h"


__attribute__((visibility("hidden")))
@interface UICachedDeviceRGBColor : UIDeviceRGBColor {
}
-(void)release;
-(id)retain;
-(unsigned)retainCount;
-(id)autorelease;
-(id)copyWithZone:(NSZone*)zone;
-(id)copy;
-(void)dealloc;
-(void)finalize;
@end

