/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIFont.h"


__attribute__((visibility("hidden")))
@interface UICFFont : UIFont {
}
-(BOOL)isEqual:(id)equal;
-(unsigned)hash;
-(id)retain;
-(oneway void)release;
-(unsigned)retainCount;
-(void)finalize;
@end

