/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIView.h"

@class UIImageView;

__attribute__((visibility("hidden")))
@interface UIClippedImageView : UIView {
@private
	UIImageView* m_imageView;
	CGRect m_originalFrame;
	CGRect m_baseFrame;
}
-(id)initWithFrame:(CGRect)frame image:(id)image;
-(void)dealloc;
-(id)image;
-(void)setImage:(id)image;
-(void)setOpaque:(BOOL)opaque;
-(void)setFrame:(CGRect)frame;
-(void)setBaseFrame:(CGRect)frame;
-(CGRect)baseFrame;
-(void)setImageOrigin:(CGPoint)origin;
-(void)setOriginAdjustingImage:(CGPoint)image;
@end

