/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIView.h"

@class UICompletionTablePrivate;

@interface UICompletionTable : UIView {
	UICompletionTablePrivate* _private;
}
+(id)_cellFont;
+(id)_shadowImage;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)layoutSubviews;
-(void)setDelegate:(id)delegate;
-(void)reloadData;
-(void)setTopStrokeColor:(id)color;
-(int)numberOfRowsInTable:(id)table;
-(id)_completionForRow:(int)row;
-(id)table:(id)table cellForRow:(int)row column:(id)column reusing:(id)reusing;
-(void)tableSelectionDidChange:(id)tableSelection;
@end

