/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>

@class UIView, UIShadowView, UITable;

__attribute__((visibility("hidden")))
@interface UICompletionTablePrivate : NSObject {
@private
	id _delegate;
	UITable* _table;
	UIShadowView* _shadowView;
	UIView* _topStrokeView;
}
-(void)dealloc;
@end

