/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIColor.h"
#import <Foundation/NSObject.h>
#import "NSCoding.h"
#import "UIKit-Structs.h"


@interface UIColor : NSObject <NSCoding> {
}
@property(readonly, assign, nonatomic) CGColorRef CGColor;
+(void)initialize;
+(id)allocWithZone:(NSZone*)zone;
+(id)colorWithWhite:(float)white alpha:(float)alpha;
+(id)colorWithHue:(float)hue saturation:(float)saturation brightness:(float)brightness alpha:(float)alpha;
+(id)colorWithRed:(float)red green:(float)green blue:(float)blue alpha:(float)alpha;
+(id)colorWithCGColor:(CGColorRef)cgcolor;
+(id)colorWithPatternImage:(id)patternImage;
+(id)blackColor;
+(id)darkGrayColor;
+(id)lightGrayColor;
+(id)whiteColor;
+(id)grayColor;
+(id)clearColor;
+(id)redColor;
+(id)greenColor;
+(id)blueColor;
+(id)cyanColor;
+(id)yellowColor;
+(id)magentaColor;
+(id)orangeColor;
+(id)purpleColor;
+(id)brownColor;
+(id)lightTextColor;
+(id)darkTextColor;
+(id)tableSeparatorDarkColor;
+(id)tableSeparatorLightColor;
+(id)tableBackgroundColor;
+(id)tableSelectionColor;
+(id)sectionListBorderColor;
+(id)sectionHeaderBackgroundColor;
+(id)sectionHeaderOpaqueBackgroundColor;
+(id)sectionHeaderBorderColor;
+(id)tableCellBlueTextColor;
+(id)tableCellValue1BlueColor;
+(id)tableCellValue2BlueColor;
+(id)tableCellGrayTextColor;
+(id)textFieldAtomBlueColor;
+(id)textFieldAtomPurpleColor;
+(id)infoTextOverPinStripeTextColor;
-(id)initWithWhite:(float)white alpha:(float)alpha;
-(id)initWithHue:(float)hue saturation:(float)saturation brightness:(float)brightness alpha:(float)alpha;
-(id)initWithRed:(float)red green:(float)green blue:(float)blue alpha:(float)alpha;
-(id)initWithCGColor:(CGColorRef)cgcolor;
-(id)initWithPatternImage:(id)patternImage;
-(Class)classForCoder;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)set;
-(void)setFill;
-(void)setStroke;
-(id)colorWithAlphaComponent:(float)alphaComponent;
-(BOOL)isEqual:(id)equal;
-(unsigned)hash;
-(CGColorRef)cgColor;
-(id)styleString;
@end

@interface UIColor (UIColorSystemColorsPrivate)
+(id)underPageBackgroundColor;
@end

@interface UIColor (UIColorSystemColors)
+(id)pinStripeColor;
+(id)selectionTintColor;
+(id)textCaretColor;
+(id)selectionCaretColor;
+(id)selectionHighlightColor;
+(id)groupTableViewBackgroundColor;
+(id)viewFlipsideBackgroundColor;
@end

