/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIView.h"

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface UICompositeImageView : UIView {
@private
	NSMutableArray* m_images;
}
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)addImage:(id)image;
-(void)addImage:(id)image operation:(int)operation fraction:(float)fraction;
-(void)addImage:(id)image toRect:(CGRect)rect fromRect:(CGRect)rect3;
-(void)addImage:(id)image toRect:(CGRect)rect fromRect:(CGRect)rect3 operation:(int)operation fraction:(float)fraction;
-(void)removeAllImages;
-(void)drawRect:(CGRect)rect;
@end

