/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface UICustomObject : NSObject {
}
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
@end

