/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>

@class NSString, NSTimer;

__attribute__((visibility("hidden")))
@interface UIDelayedAction : NSObject {
@private
	id m_target;
	SEL m_action;
	id m_userInfo;
	double m_delay;
	NSTimer* m_timer;
	BOOL m_canceled;
	NSString* m_runLoopMode;
}
-(id)initWithTarget:(id)target action:(SEL)action userInfo:(id)info delay:(double)delay mode:(id)mode;
-(id)initWithTarget:(id)target action:(SEL)action userInfo:(id)info delay:(double)delay;
-(void)dealloc;
-(void)touch;
-(void)touchWithDelay:(double)delay;
-(void)cancel;
-(void)unschedule;
-(id)userInfo;
-(BOOL)scheduled;
-(void)setTarget:(id)target;
-(id)target;
-(double)delay;
-(void)timerFired:(id)fired;
@end

