/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIControlTargetAction.h"

@class UIEvent;

__attribute__((visibility("hidden")))
@interface UIDelayedControlTargetAction : UIControlTargetAction {
@private
	UIEvent* _event;
}
-(void)dealloc;
@end

