/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIView.h"


__attribute__((visibility("hidden")))
@interface UIDimmingView : UIView {
@private
	id _delegate;
	CGGradientRef _gradient;
}
@property(assign, nonatomic) id delegate;
+(id)dimmingViewForView:(id)view;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)drawRect:(CGRect)rect;
-(void)transitionDidStop:(id)transition finished:(id)finished context:(id)context;
-(void)display:(BOOL)display withAnimationDuration:(float)animationDuration;
-(void)mouseUp:(GSEventRef)up;
-(void)touchesEnded:(id)ended withEvent:(id)event;
@end

