/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UISelectedItemPrivate.h"
#import <Foundation/NSObject.h>

@class DOMHTMLOptGroupElement;

__attribute__((visibility("hidden")))
@interface UIDOMHTMLOptGroupSelectedItem : NSObject <UISelectedItemPrivate> {
@private
	DOMHTMLOptGroupElement* _node;
}
@property(retain, nonatomic) DOMHTMLOptGroupElement* _node;
-(id)initWithHTMLOptGroupNode:(id)htmloptGroupNode;
-(id)node;
-(BOOL)selected;
-(void)setSelected:(BOOL)selected;
-(void)unselect;
-(void)dealloc;
@end

