/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UISelectedItemPrivate.h"
#import <Foundation/NSObject.h>

@class DOMHTMLOptionElement;

__attribute__((visibility("hidden")))
@interface UIDOMHTMLOptionSelectedItem : NSObject <UISelectedItemPrivate> {
@private
	BOOL _selected;
	DOMHTMLOptionElement* _node;
}
@property(retain, nonatomic) DOMHTMLOptionElement* _node;
-(id)initWithHTMLOptionNode:(id)htmloptionNode;
-(id)node;
-(BOOL)selected;
-(void)setSelected:(BOOL)selected;
-(void)unselect;
-(void)dealloc;
@end

