/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIGestureRecognizer.h"

@class UITouch, UIDelayedAction;

__attribute__((visibility("hidden")))
@interface UIDragRecognizer : UIGestureRecognizer {
@private
	double _maximumDeviation;
	double _minimumDistance;
	CGPoint _startPosition;
	BOOL _restrictsToAngle;
	double _angle;
	UITouch* _touch;
	UIDelayedAction* _tooSlow;
	double _startAngle;
}
@property(assign, nonatomic) double maximumDeviation;
@property(assign, nonatomic) CGPoint startPosition;
@property(assign, nonatomic) double minimumDistance;
@property(retain, nonatomic) UITouch* touch;
@property(assign, nonatomic) BOOL restrictsToAngle;
@property(assign, nonatomic) double angle;
@property(assign, nonatomic) double startAngle;
-(id)initWithTarget:(id)target action:(SEL)action;
-(void)dealloc;
-(void)reset;
-(void)clearTimer;
-(void)tooSlow:(id)slow;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
@end

