/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>
#import "UIEvent.h"
#import "UIKit-Structs.h"


@interface UIEvent : NSObject {
@private
	double _timestamp;
}
@property(readonly, assign, nonatomic) double timestamp;
@property(readonly, assign, nonatomic) int subtype;
@property(readonly, assign, nonatomic) int type;
-(id)allTouches;
-(id)touchesForWindow:(id)window;
-(id)touchesForView:(id)view;
@end

@interface UIEvent (UIEventInternal)
-(id)_init;
-(void)_setTimestamp:(double)timestamp;
@end

@interface UIEvent (UIEventPrivate)
-(id)_initWithEvent:(GSEventRef)event touches:(id)touches;
-(GSEventRef)_gsEvent;
-(id)_touchesForGestureRecognizer:(id)gestureRecognizer;
-(int)_shakeState;
@end

