/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>
#import "UIKit-Structs.h"

@class UIView;

@interface UIFlicker : NSObject {
	UIView* _target;
	CGPoint _startLocation;
	int _throwIterations;
	id _delegate;
	int _mouseUpCount;
	int _mouseDraggedCount;
	float _delay;
	CGPoint _offset;
}
-(void)_mouseDraggedMemberListTest;
-(void)_mouseUpMemberListTest;
-(void)_throwMemberListTest;
-(id)init;
-(CGPoint)offset;
-(void)setOffset:(CGPoint)offset;
-(void)setTarget:(id)target;
-(void)setStartLocation:(CGPoint)location;
-(void)setIterations:(int)iterations;
-(void)setDelay:(float)delay;
-(void)setDelegate:(id)delegate;
-(void)run;
@end

