/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIView.h"
#import "UIKit-Structs.h"
#import "UITextFieldDelegate.h"

@class UITextField, UITable;

__attribute__((visibility("hidden")))
@interface UIFontChooser : UIView <UITextFieldDelegate> {
@private
	UITable* _nameTable;
	UITable* _sizeTable;
	UITextField* _sizeField;
	CFArrayRef _familyNames;
	id _delegate;
	unsigned _sizes[15];
	unsigned _sizeBeforeEditing;
}
+(id)sharedFontChooser;
-(id)_tableWithFrame:(CGRect)frame;
-(CGRect)_nameTableFrame;
-(CGRect)_separatorFrame;
-(CGRect)_fieldBackgroundFrame;
-(CGRect)_sizeFieldFrame;
-(CGRect)_sizeTableFrame;
-(void)_updateSublayerFrames;
-(id)initWithFrame:(CGRect)frame;
-(void)setFrame:(CGRect)frame;
-(void)drawRect:(CGRect)rect;
-(int)numberOfRowsInTable:(id)table;
-(id)table:(id)table cellForRow:(int)row column:(id)column;
-(void)selectFamilyName:(id)name;
-(void)selectSize:(float)size;
-(void)selectFont:(id)font;
-(void)acceptSizeFromSizeField;
-(void)_finishedEditing:(id)editing;
-(void)tableSelectionDidChange:(id)tableSelection;
-(void)textFieldDidBecomeFirstResponder:(id)textField;
-(void)textFieldDidResignFirstResponder:(id)textField;
-(id)selectedFamilyName;
-(float)selectedSize;
-(void)setDelegate:(id)delegate;
-(id)delegate;
@end

