/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */



@protocol UIFormPeripheral
-(void)setPeripheralFormNode:(id)node;
-(void)beginEditing;
-(void)endEditing;
-(void)reset;
-(id)peripheralFormNode;
-(BOOL)isKeyboard;
@end

