/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "NSObject.h"


@protocol UIFormAssistantDelegate <NSObject>
-(void)formAssistant:(id)assistant didBeginEditingFormNode:(id)node;
-(void)formAssistant:(id)assistant didEndEditingFormNode:(id)node;
@end

