/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>

@class NSString;

@interface UIFont : NSObject {
}
@property(readonly, assign, nonatomic) float xHeight;
@property(readonly, assign, nonatomic) float capHeight;
@property(readonly, assign, nonatomic) float leading;
@property(readonly, assign, nonatomic) float descender;
@property(readonly, assign, nonatomic) float ascender;
@property(readonly, assign, nonatomic) float pointSize;
@property(readonly, retain, nonatomic) NSString* fontName;
@property(readonly, retain, nonatomic) NSString* familyName;
+(id)__dummy;
+(id)fontWithName:(id)name size:(float)size;
+(id)fontWithFamilyName:(id)familyName traits:(int)traits size:(float)size;
+(id)fontWithMarkupDescription:(id)markupDescription;
+(id)familyNames;
+(id)fontNamesForFamilyName:(id)familyName;
+(id)systemFontOfSize:(float)size;
+(id)boldSystemFontOfSize:(float)size;
+(id)italicSystemFontOfSize:(float)size;
+(float)labelFontSize;
+(float)buttonFontSize;
+(float)smallSystemFontSize;
+(float)systemFontSize;
-(id)initWithName:(id)name size:(float)size;
-(id)initWithFamilyName:(id)familyName traits:(int)traits size:(float)size;
-(id)initWithMarkupDescription:(id)markupDescription;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(Class)classForCoder;
-(id)fontWithSize:(float)size;
-(int)traits;
-(BOOL)isFixedPitch;
-(id)markupDescription;
@end

