/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIAnimation.h"


__attribute__((visibility("hidden")))
@interface UIGestureAnimation : UIAnimation {
@private
	SEL _progressSelector;
	int _gestureType;
}
-(id)initWithTarget:(id)target progressSelector:(SEL)selector gestureType:(int)type;
-(void)setProgress:(float)progress;
-(int)gestureType;
@end

