/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>

@class UIEvent, UITouch;

__attribute__((visibility("hidden")))
@interface UIGestureDelayedTouch : NSObject {
@private
	UITouch* _touch;
	UITouch* _touchState;
	UITouch* _savedTouchState;
	UIEvent* _event;
}
@property(retain) UITouch* touch;
@property(retain) UITouch* touchState;
@property(retain) UITouch* savedTouchState;
@property(retain) UIEvent* event;
-(id)init;
-(void)dealloc;
@end

