/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import <Foundation/NSObject.h>


@interface UIGradient : NSObject {
	XXStruct_iyXfGC* _values;
	float _height;
	CGShadingRef _shader;
}
-(id)initVerticalWithValues:(XXStruct_iyXfGC*)values;
-(void)fillRect:(CGRect)rect inContext:(CGContextRef)context;
-(void)fillRect:(CGRect)rect;
-(void)dealloc;
@end

