/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>
#import "UIKit-Structs.h"


@interface UIGroupInsertionItem : NSObject {
@private
	int _index;
	NSRange _range;
}
-(id)initWithExistingGroup:(int)existingGroup andRowRange:(NSRange)range;
-(id)initWithNewGroupBeforeGroup:(int)newGroupBeforeGroup andRowCount:(int)count;
-(int)groupIndex;
-(NSRange)range;
@end

