/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIView.h"
#import "UIKit-Structs.h"

@class UIColor, NSArray, NSMutableArray;

__attribute__((visibility("hidden")))
@interface UIHighlightView : UIView {
@private
	UIColor* _color;
	float _cornerRadius;
	CGRect _invertedHighlightClipRect;
	NSArray* _cornerRadii;
	NSMutableArray* _innerBounds;
	NSMutableArray* _innerQuads;
	BOOL _invertHighlight;
}
-(id)initWithFrame:(CGRect)frame;
-(void)cleanUp;
-(void)dealloc;
-(void)setColor:(id)color;
-(void)setCornerRadius:(float)radius;
-(void)setCornerRadii:(id)radii;
-(void)setFrames:(id)frames boundaryRect:(CGRect)rect;
-(void)setQuads:(id)quads boundaryRect:(CGRect)rect;
-(void)setFrame:(CGRect)frame;
-(void)setInvertHighlight:(BOOL)highlight clipRect:(CGRect)rect;
-(void)drawRect:(CGRect)rect;
-(id)hitTest:(CGPoint)test forEvent:(GSEventRef)event;
@end

