/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIView.h"
#import "UIKit-Structs.h"
#import "UIImageView.h"

@class UIImage, NSArray;

@interface UIImageView : UIView {
@private
	id _storage;
}
@property(assign, nonatomic, getter=isUserInteractionEnabled) BOOL userInteractionEnabled;
@property(assign, nonatomic) int animationRepeatCount;
@property(assign, nonatomic) double animationDuration;
@property(copy, nonatomic) NSArray* highlightedAnimationImages;
@property(copy, nonatomic) NSArray* animationImages;
@property(assign, nonatomic, getter=isHighlighted) BOOL highlighted;
@property(retain, nonatomic) UIImage* highlightedImage;
@property(retain, nonatomic) UIImage* image;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithImage:(id)image;
-(id)initWithImage:(id)image highlightedImage:(id)image2;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)dealloc;
-(void)setBounds:(CGRect)bounds;
-(void)setFrame:(CGRect)frame;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)drawRect:(CGRect)rect;
-(void)startAnimating;
-(void)stopAnimating;
-(BOOL)isAnimating;
@end

@interface UIImageView (UIImageViewPrivate)
@property(assign, nonatomic) int drawMode;
-(void)setCGImageRef:(CGImageRef)ref;
-(CGImageRef)imageRef;
-(void)setAnimating:(BOOL)animating;
@end

@interface UIImageView (UIImageViewInternal)
-(BOOL)_canDrawContent;
-(void)_updateState;
@end

@interface UIImageView (UIKitAccessibilityInterfaceBuilderSupport)
-(BOOL)isAccessibilityElementByDefault;
-(unsigned long long)defaultAccessibilityTraits;
-(BOOL)isElementAccessibilityExposedToInterfaceBuilder;
@end

