/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "NSCoding.h"
#import "UIImage.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface UIImageNibPlaceholder : UIImage <NSCoding> {
@private
	NSString* runtimeResourceName;
}
-(id)initWithContentsOfFile:(id)file andRuntimeResourceName:(id)name;
-(id)initWithData:(id)data andRuntimeResourceName:(id)name;
-(void)dealloc;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
@end

