/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface UIImageBuffer : NSObject {
@private
	unsigned m_width;
	unsigned m_height;
	unsigned m_pixelCount;
	unsigned m_componentCount;
	UIEdgeInsets* m_pixels;
}
@property(readonly, assign, nonatomic) unsigned width;
@property(readonly, assign, nonatomic) unsigned height;
-(id)initWithWidth:(unsigned)width height:(unsigned)height;
-(void)dealloc;
-(UIEdgeInsets*)pixels;
-(void)getPixel:(UIEdgeInsets*)pixel atPoint:(CGPoint)point;
-(void)setPixel:(UIEdgeInsets*)pixel atPoint:(CGPoint)point;
-(void)fillWithPixel:(UIEdgeInsets*)pixel;
-(CGImageRef)createImage;
@end

