/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>


@interface UIInformalDelegate : NSObject {
	id _target;
	id _default;
}
+(id)informalDelegateWithDefaultTarget:(id)defaultTarget;
-(id)initWithDefaultTarget:(id)defaultTarget;
-(void)dealloc;
-(void)setTarget:(id)target;
-(id)target;
-(void)forwardInvocation:(id)invocation;
-(id)methodSignatureForSelector:(SEL)selector;
-(BOOL)respondsToSelector:(SEL)selector;
@end

