/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>

@class NSArray;

__attribute__((visibility("hidden")))
@interface UIITunesStoreURLResolver : NSObject {
@private
	NSArray* _appStoreHostPatterns;
	NSArray* _appStorePathPatterns;
	NSArray* _hostWhiteList;
	NSArray* _musicStoreHostPatterns;
	NSArray* _musicStorePathPatterns;
}
+(void)invalidate;
+(id)sharedResolver;
-(id)init;
-(void)dealloc;
-(int)urlTypeForURL:(id)url;
-(id)_copyRegularExpressionsFromArray:(id)array;
-(BOOL)_string:(id)string matchesPatterns:(id)patterns;
-(BOOL)_url:(id)url matchesHostPatterns:(id)patterns pathPatterns:(id)patterns3;
@end

