/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIView.h"

@class UIKBKey, UIKBKeyboard;

__attribute__((visibility("hidden")))
@interface UIKBKeyView : UIView {
@private
	UIKBKeyboard* m_keyboard;
	UIKBKey* m_key;
	int m_state;
	CGPoint m_drawOrigin;
}
@property(readonly, assign, nonatomic) UIKBKeyboard* keyboard;
@property(readonly, assign, nonatomic) UIKBKey* key;
@property(readonly, assign, nonatomic) int state;
@property(assign, nonatomic) CGPoint drawOrigin;
-(id)initWithFrame:(CGRect)frame keyboard:(id)keyboard key:(id)key state:(int)state;
-(void)dealloc;
-(void)drawRect:(CGRect)rect;
@end

