/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>
#import "NSCoding.h"

@class NSMutableArray, NSString;

@interface UIKBKeylist : NSObject <NSCoding> {
	NSString* m_name;
	NSMutableArray* m_keys;
}
@property(retain, nonatomic) NSString* name;
@property(retain, nonatomic) NSMutableArray* keys;
@property(readonly, assign, nonatomic) unsigned count;
+(id)keylist;
-(id)init;
-(void)dealloc;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(id)keyWithName:(id)name;
-(id)description;
@end

