/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>
#import "NSCoding.h"

@class NSString;

@interface UIKBAttribute : NSObject <NSCoding> {
	NSString* m_name;
	id m_value;
}
@property(copy, nonatomic) NSString* name;
@property(copy, nonatomic) id value;
+(id)attributeWithName:(id)name value:(id)value;
-(id)initWithName:(id)name value:(id)value;
-(void)dealloc;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
@end

