/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIView.h"

@class UIKBKeyplane, NSString, UIKBKeyboard;

__attribute__((visibility("hidden")))
@interface UIKBKeyplaneView : UIView {
@private
	UIKBKeyboard* m_keyboard;
	UIKBKeyplane* m_keyplane;
	NSString* m_visualStyle;
}
@property(retain, nonatomic) UIKBKeyplane* keyplane;
@property(readonly, assign, nonatomic) NSString* visualStyle;
-(id)initWithFrame:(CGRect)frame keyboard:(id)keyboard keyplane:(id)keyplane;
-(void)dealloc;
-(BOOL)validForKeyplane:(id)keyplane withVisualStyle:(id)visualStyle;
-(void)drawRect:(CGRect)rect;
@end

