/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIView.h"


__attribute__((visibility("hidden")))
@interface UIKeyboardCandidateShadowView : UIView {
@private
	BOOL _landscape;
}
-(id)initWithFrame:(CGRect)frame;
-(void)setLandscape:(BOOL)landscape;
-(void)drawRect:(CGRect)rect;
@end

