/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIScroller.h"


__attribute__((visibility("hidden")))
@interface UIKeyboardCandidateInlineScroller : UIScroller {
@private
	UIView* _savedLastHighlightedView;
}
-(void)mouseUp:(GSEventRef)up;
-(void)mouseDown:(GSEventRef)down;
-(void)contentMouseUpInView:(id)view withEvent:(GSEventRef)event;
@end

