/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>

@class NSString, NSArray;

__attribute__((visibility("hidden")))
@interface UIKeyboardEmojiCategory : NSObject {
@private
	NSString* _name;
	NSArray* _emoji;
	int _lastViewedPage;
}
@property(retain) NSString* name;
@property(retain) NSArray* emoji;
@property(assign) int lastViewedPage;
@end

