/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIKeyboardKeyView.h"


@interface UIKeyboardReturnKeyView : UIKeyboardKeyView {
	int m_originalStyle;
	int m_subtype;
}
-(id)initWithFrame:(CGRect)frame orientation:(int)orientation style:(int)style;
-(CFDataRef)createCacheKey;
-(int)subtype;
-(void)setSubtype:(int)subtype;
-(id)localizedString;
-(id)symbolString;
@end

