/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>

@class NSDictionary, NSMutableDictionary;
@protocol UIKeyboardEmojiController;

__attribute__((visibility("hidden")))
@interface UIKeyboardEmojiCategoryController : NSObject {
@private
	id<UIKeyboardEmojiController> emojiController;
	NSMutableDictionary* categories;
	NSMutableDictionary* _defaultsData;
}
@property(retain) NSDictionary* defaultsData;
-(id)initWithController:(id)controller;
-(void)dealloc;
-(id)categoryForKey:(id)key;
-(void)updateRecents;
@end

