/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIKeyboardKeyView.h"


@interface UIKeyboardSpaceKeyView : UIKeyboardKeyView {
}
-(id)initWithFrame:(CGRect)frame orientation:(int)orientation style:(int)style;
-(id)localizedString;
-(id)symbolString;
@end

