/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKeyboard.h"
#import "UIFormPeripheral.h"

@class DOMNode;

__attribute__((visibility("hidden")))
@interface UIKeyboardPeripheral : UIKeyboard <UIFormPeripheral> {
@private
	DOMNode* _textNode;
	int _orientation;
}
@property(retain, nonatomic) DOMNode* _textNode;
+(id)createPeripheral;
-(id)initFormPeripheral;
-(void)dealloc;
-(id)peripheralFormNode;
-(BOOL)isKeyboard;
-(void)beginEditing;
-(void)endEditing;
-(void)reset;
-(void)setPeripheralFormNode:(id)node;
-(int)orientation;
-(void)resumeWithNotification:(id)notification;
@end

