/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "NSCoding.h"
#import "UIView.h"


__attribute__((visibility("hidden")))
@interface UILayoutContainerView : UIView <NSCoding> {
@private
	id _delegate;
}
@property(assign, nonatomic) id delegate;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)setFrame:(CGRect)frame;
-(void)layoutSubviews;
@end

