/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIView.h"
#import "UIKit-Structs.h"

@class NSDictionary, NSMutableDictionary, NSArray, UIMovieScrubberTrackOverlayView;
@protocol UIMovieScrubberTrackViewDelegate, UIMovieScrubberTrackViewDataSource;

__attribute__((visibility("hidden")))
@interface UIMovieScrubberTrackView : UIView {
@private
	id<UIMovieScrubberTrackViewDataSource> _dataSource;
	id<UIMovieScrubberTrackViewDelegate> _delegate;
	NSArray* _summaryThumbnailViews;
	NSArray* _summaryThumbnailTimestamps;
	NSArray* _summaryThumbnailChildTimestamps;
	NSDictionary* _thumbnailStartXValues;
	NSDictionary* _childThumbnailViews;
	NSMutableDictionary* _thumbnailViews;
	NSArray* _timestamps;
	UIMovieScrubberTrackOverlayView* _overlayView;
	UIView* _maskView;
	UIView* _maskContainerView;
	CGSize _thumbnailSize;
	float _zoomOriginXDelta;
	float _zoomWidthDelta;
	float _unclampedZoomWidthDelta;
	float _zoomAnimationDuration;
	double _duration;
	double _value;
	double _startValue;
	double _endValue;
	struct {
		unsigned delegateSizeOriginDelta : 1;
		unsigned delegateDidExpand : 1;
		unsigned delegateDidCollapse : 1;
		unsigned delegateWillRequestThumbs : 1;
		unsigned delegateDidRequestThumbs : 1;
		unsigned delegateZoomAnimationDuration : 1;
		unsigned delegateZoomAnimationDelay : 1;
		unsigned needsReload : 1;
		unsigned editing : 1;
		unsigned editingHandle;
		unsigned zoomIsDisabled : 1;
	} _trackFlags;
}
@property(assign, nonatomic) id<UIMovieScrubberTrackViewDelegate> delegate;
@property(assign, nonatomic) id<UIMovieScrubberTrackViewDataSource> dataSource;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)drawRect:(CGRect)rect;
-(void)setFrame:(CGRect)frame;
-(void)setValue:(double)value;
-(void)setEditing:(BOOL)editing;
-(void)animateFillFramesAway;
-(void)setStartValue:(double)value;
-(void)setEndValue:(double)value;
-(void)setThumbnailImage:(CGImageRef)image forTimestamp:(id)timestamp;
-(id)_createImageViewForTimestamp:(id)timestamp;
-(void)clear;
-(void)_reallyReloadData;
-(void)reloadData;
-(void)layoutSubviews;
-(void)setZoomAnimationDuration:(float)duration;
-(float)zoomAnimationDuration;
-(BOOL)zoomAtPoint:(CGPoint)point;
-(void)_setOverlayViewIsZoomed:(BOOL)zoomed minValue:(float)value maxValue:(float)value3;
-(void)unzoom;
-(void)_zoomAnimation:(id)animation didFinish:(id)finish context:(void*)context;
-(void)_unzoomAnimation:(id)animation didFinish:(id)finish context:(void*)context;
@end

