/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIViewController.h"

@class UIView, UINavigationBar, UINavigationTransitionView, NSArray, NSMutableArray, UIToolbar;
@protocol UINavigationControllerDelegate;

@interface UINavigationController : UIViewController {
@private
	UIView* _containerView;
	UINavigationBar* _navigationBar;
	Class _navigationBarClass;
	UIToolbar* _toolbar;
	UIView* _navigationTransitionView;
	UIEdgeInsets _currentScrollContentInsetDelta;
	UIEdgeInsets _previousScrollContentInsetDelta;
	float _previousScrollContentOffsetDelta;
	float _bottomInsetDelta;
	NSMutableArray* _viewControllers;
	UIViewController* _disappearingViewController;
	id<UINavigationControllerDelegate> _delegate;
	struct {
		unsigned isAppearingAnimated : 1;
		unsigned isAlreadyPoppingNavigationItem : 1;
		unsigned isNavigationBarHidden : 1;
		unsigned isToolbarShown : 1;
		unsigned needsDeferredTransition : 1;
		unsigned isTransitioning : 1;
		unsigned lastOperation : 4;
		unsigned lastOperationAnimated : 1;
		unsigned deferredTransition : 8;
		unsigned didPreloadKeyboardAnimation : 1;
		unsigned didHideBottomBar : 1;
		unsigned isChangingOrientationForPop : 1;
	} _navigationControllerFlags;
}
@property(assign, nonatomic) id<UINavigationControllerDelegate> delegate;
@property(retain, nonatomic) UIViewController* disappearingViewController;
@property(readonly, assign, nonatomic) UINavigationTransitionView* navigationTransitionView;
@property(assign, nonatomic) BOOL needsDeferredTransition;
@property(readonly, assign, nonatomic) UIViewController* bottomViewController;
@property(readonly, assign, nonatomic) UIViewController* previousViewController;
@property(readonly, assign, nonatomic) UIToolbar* toolbar;
@property(assign, nonatomic, getter=isToolbarHidden) BOOL toolbarHidden;
@property(readonly, assign, nonatomic) UINavigationBar* navigationBar;
@property(assign, nonatomic, getter=isNavigationBarHidden) BOOL navigationBarHidden;
@property(copy, nonatomic) NSArray* viewControllers;
@property(readonly, retain, nonatomic) UIViewController* visibleViewController;
@property(readonly, retain, nonatomic) UIViewController* topViewController;
-(id)initWithRootViewController:(id)rootViewController;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
-(id)initWithCoder:(id)coder;
-(BOOL)_shouldPersistViewWhenCoding;
-(void)encodeWithCoder:(id)coder;
-(void)_releaseContainerViews;
-(void)dealloc;
-(int)modalTransitionStyle;
-(int)_transitionForOldViewControllers:(id)oldViewControllers newViewControllers:(id)controllers;
-(void)setViewControllers:(id)controllers animated:(BOOL)animated;
-(id)_navigationItems;
-(void)_setViewControllers:(id)controllers transition:(int)transition;
-(Class)navigationBarClass;
-(void)setNavigationBarClass:(Class)aClass;
-(void)setNavigationBar:(id)bar;
-(BOOL)_animationParametersForHidingNavigationBar:(BOOL)hidingNavigationBar lastOperation:(int)operation edge:(int*)edge duration:(double*)duration;
-(void)setNavigationBarHidden:(BOOL)hidden animated:(BOOL)animated;
-(void)_setNavigationBarHidden:(BOOL)hidden edgeIfNotNavigating:(int)navigating duration:(double)duration;
-(void)_positionNavigationBarHidden:(BOOL)hidden;
-(void)_positionNavigationBarHidden:(BOOL)hidden edge:(int)edge;
-(void)_setNavigationBarHidden:(BOOL)hidden edge:(int)edge duration:(double)duration;
-(void)_hideShowNavigationBarDidStop:(id)_hideShowNavigationBar finished:(id)finished context:(void*)context;
-(id)_existingToolbar;
-(void)_configureToolbar;
-(void)setToolbar:(id)toolbar;
-(void)setToolbarHidden:(BOOL)hidden animated:(BOOL)animated;
-(void)_positionToolbarHidden:(BOOL)hidden;
-(void)_positionToolbarHidden:(BOOL)hidden edge:(int)edge;
-(void)_setToolbarHidden:(BOOL)hidden edge:(int)edge duration:(double)duration;
-(void)_hideShowToolbarDidStop:(id)_hideShowToolbar finished:(id)finished context:(void*)context;
-(void)loadView;
-(BOOL)isShown;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidMoveToWindow:(id)view shouldAppearOrDisappear:(BOOL)disappear;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidDisappear:(BOOL)view;
-(void)purgeMemoryForReason:(int)reason;
-(void)viewDidUnload;
-(void)setEditing:(BOOL)editing animated:(BOOL)animated;
-(BOOL)editing;
-(void)_updateToolbarItemsFromViewController:(id)viewController animated:(BOOL)animated;
-(BOOL)_reallyWantsFullScreenLayout;
-(void)willShowViewController:(id)controller animated:(BOOL)animated;
-(void)didShowViewController:(id)controller animated:(BOOL)animated;
-(void)navigationTransitionView:(id)view didEndTransition:(int)transition fromView:(id)view3 toView:(id)view4;
-(double)navigationTransitionView:(id)view durationForTransition:(int)transition;
-(void)setNeedsDeferredTransition;
-(int)lastOperation;
-(BOOL)wasLastOperationAnimated;
-(void)_updateBarsForCurrentInterfaceOrientation;
-(void)_updateLayoutForStatusBarAndInterfaceOrientation;
-(void)_applyScrollContentInsetDelta:(UIEdgeInsets)delta toScrollView:(id)scrollView;
-(void)_applyScrollContentOffsetDelta:(float)delta toScrollView:(id)scrollView;
-(void)_restoreOriginalInsetAndOffsetToScrollView:(id)scrollView;
-(BOOL)_hasTranslucentNavigationBarIncludingViewController:(id)controller;
-(BOOL)_isNavigationBarVisible;
-(BOOL)_shouldNavigationBarInsetViewController:(id)controller;
-(BOOL)_shouldChildViewControllerUseFullScreenLayout:(id)layout;
-(CGRect)_frameForViewController:(id)viewController;
-(void)_layoutTopViewController;
-(void)_computeAndApplyScrollContentInsetDeltaForViewController:(id)viewController;
-(void)_layoutViewController:(id)controller;
-(int)_navigationTransitionForUITransition:(int)uitransition;
-(void)_startTransition:(int)transition fromViewController:(id)viewController toViewController:(id)viewController3;
-(void)_startDeferredTransitionIfNeeded;
-(int)_deferredTransition;
-(void)_clearLastOperation;
-(void)viewWillLayoutSubviews;
-(void)pushViewController:(id)controller animated:(BOOL)animated;
-(void)pushViewController:(id)controller transition:(int)transition forceImmediate:(BOOL)immediate;
-(void)pushViewController:(id)controller transition:(int)transition;
-(id)popViewControllerAnimated:(BOOL)animated;
-(BOOL)_shouldBottomBarBeHidden;
-(void)_resetBottomBarHiddenState;
-(void)_updateBottomBarHiddenState;
-(void)_hideOrShowBottomBarIfNeededWithTransition:(int)transition;
-(void)_tabBarControllerDidFinishShowingTabBar:(id)_tabBarController;
-(id)_snapshotView;
-(BOOL)_shouldPopFromLandscapeToPortraitOrientation;
-(void)_popViewControllerAndUpdateInterfaceOrientationAnimated:(BOOL)animated;
-(id)_popViewControllerWithTransition:(int)transition allowPoppingLast:(BOOL)last;
-(id)popViewControllerWithAnimationTransition:(int)animationTransition duration:(double)duration curve:(int)curve;
-(id)popViewControllerWithTransition:(int)transition;
-(id)popToRootViewControllerAnimated:(BOOL)rootViewControllerAnimated;
-(id)popToRootViewControllerWithTransition:(int)transition;
-(id)popToViewController:(id)viewController animated:(BOOL)animated;
-(id)popToViewController:(id)viewController transition:(int)transition;
-(id)popToViewControllerWithSnapbackIdentifier:(id)snapbackIdentifier animated:(BOOL)animated;
-(void)makeModalViewControllerTopViewController;
-(BOOL)_allowsAutorotation;
-(BOOL)_doesTopViewControllerSupportInterfaceOrientation:(int)orientation;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(BOOL)_isSupportedInterfaceOrientation:(int)orientation;
-(id)rotatingHeaderView;
-(id)rotatingFooterView;
-(BOOL)_shouldUseOnePartRotation;
-(void)_getRotationContentSettings:(XXStruct_TF$i3B*)settings;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)willAnimateFirstHalfOfRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)didAnimateFirstHalfOfRotationToInterfaceOrientation:(int)interfaceOrientation;
-(void)willAnimateSecondHalfOfRotationFromInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)updateTitleForViewController:(id)viewController;
-(BOOL)navigationBar:(id)bar shouldPopItem:(id)item;
-(void)navigationBar:(id)bar buttonClicked:(int)clicked;
-(void)navigationBarDidResizeForPrompt:(id)navigationBar;
-(void)navigationBarDidChangeOpacity:(id)navigationBar;
-(id)defaultPNGName;
-(id)tabBarItem;
-(void)updateTabBarItemForViewController:(id)viewController;
-(id)_moreListTitle;
-(id)moreListImage;
-(id)moreListSelectedImage;
-(id)moreListTableCell;
@end

