/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>
#import "NSCoding.h"

@class NSString, UINavigationBar, UIView, UIBarButtonItem;

@interface UINavigationItem : NSObject <NSCoding> {
@private
	NSString* _title;
	NSString* _backButtonTitle;
	UIBarButtonItem* _backBarButtonItem;
	NSString* _prompt;
	int _tag;
	id _context;
	UINavigationBar* _navigationBar;
	UIView* _defaultTitleView;
	UIView* _titleView;
	UIView* _backButtonView;
	UIBarButtonItem* _leftBarButtonItem;
	UIBarButtonItem* _rightBarButtonItem;
	UIView* _customLeftView;
	UIView* _customRightView;
	BOOL _hidesBackButton;
}
@property(retain, nonatomic) UIView* titleView;
@property(retain, nonatomic) UIBarButtonItem* rightBarButtonItem;
@property(retain, nonatomic) UIBarButtonItem* leftBarButtonItem;
@property(assign, nonatomic) BOOL hidesBackButton;
@property(copy, nonatomic) NSString* prompt;
@property(retain, nonatomic) UIBarButtonItem* backBarButtonItem;
@property(copy, nonatomic) NSString* title;
+(id)defaultFont;
-(id)initWithTitle:(id)title;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)dealloc;
-(id)navigationBar;
-(void)setNavigationBar:(id)bar;
-(void)setBackButtonTitle:(id)title;
-(id)backButtonTitle;
-(float)width;
-(void)setWidth:(float)width;
-(void)setFont:(id)font;
-(id)font;
-(void)setTag:(int)tag;
-(int)tag;
-(void)setContext:(id)context;
-(id)context;
-(void)_removeTitleAndButtonViews;
-(id)existingBackButtonView;
-(id)backButtonView;
-(void)updateNavigationBarButtonsAnimated:(BOOL)animated;
-(void)setHidesBackButton:(BOOL)button animated:(BOOL)animated;
-(void)setLeftBarButtonItem:(id)item animated:(BOOL)animated;
-(void)setRightBarButtonItem:(id)item animated:(BOOL)animated;
-(id)customLeftView;
-(void)setCustomLeftView:(id)view;
-(void)setCustomLeftView:(id)view animated:(BOOL)animated;
-(id)customRightView;
-(void)setCustomRightView:(id)view;
-(void)setCustomRightView:(id)view animated:(BOOL)animated;
-(id)_titleView;
-(void)setCustomTitleView:(id)view;
-(id)customTitleView;
-(void)setCustomLeftItem:(id)item;
-(id)customLeftItem;
-(void)setCustomLeftItem:(id)item animated:(BOOL)animated;
-(void)setCustomRightItem:(id)item;
-(id)customRightItem;
-(void)setCustomRightItem:(id)item animated:(BOOL)animated;
-(id)_automationID;
@end

