/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIView.h"

@class UIColor;

__attribute__((visibility("hidden")))
@interface UINavigationBarBackground : UIView {
@private
	int _barStyle;
	UIColor* _tintColor;
	struct {
		unsigned isTranslucent : 1;
	} _navbarFlags;
}
-(id)initWithFrame:(CGRect)frame withBarStyle:(int)barStyle withTintColor:(id)tintColor isTranslucent:(BOOL)translucent;
-(void)dealloc;
-(void)drawRect:(CGRect)rect;
@end

