/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIView.h"

@class NSString, UINavigationBar;

__attribute__((visibility("hidden")))
@interface UINavBarPrompt : UIView {
@private
	NSString* _prompt;
	UINavigationBar* _navBar;
}
-(id)initWithPrompt:(id)prompt navBar:(id)bar;
-(void)clearWeakReference:(id)reference;
-(void)dealloc;
-(void)setPrompt:(id)prompt;
-(id)prompt;
-(CGRect)promptBounds;
-(void)drawRect:(CGRect)rect;
@end

