/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UINavigationItemView.h"


__attribute__((visibility("hidden")))
@interface UINavigationItemButtonView : UINavigationItemView {
@private
	int _style;
	BOOL _pressed;
}
-(void)drawRect:(CGRect)rect;
-(id)title;
-(id)image;
-(CGSize)imageSize;
-(void)_styleAnimationDidStop:(id)_styleAnimation finished:(id)finished context:(id)context;
-(void)setStyle:(int)style animated:(BOOL)animated;
-(void)setStyle:(int)style;
-(void)setPressed:(BOOL)pressed;
-(BOOL)pressed;
-(id)_scriptingInfo;
-(id)_defaultFont;
@end

