/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>

@class NSData, UINibDecoder;

__attribute__((visibility("hidden")))
@interface UINib : NSObject {
@private
	NSData* archiveData;
	UINibDecoder* nibDecoder;
	BOOL instantiatingForSimulator;
}
-(id)initWithData:(id)data;
-(id)initWithContentsOfURL:(id)url;
-(id)initWithContentsOfFile:(id)file;
-(void)dealloc;
-(BOOL)instantiatingForSimulator;
-(void)setInstantiatingForSimulator:(BOOL)simulator;
-(id)instantiateWithOwner:(id)owner loadingResourcesFromBundle:(id)bundle;
-(id)unarchiverForInstantiatingReturningError:(id*)instantiatingReturningError;
-(id)instantiateWithOptions:(id)options owner:(id)owner loadingResourcesFromBundle:(id)bundle;
@end

