/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>
#import "UIKit-Structs.h"


__attribute__((visibility("hidden")))
@interface UINibStringIDTable : NSObject {
@private
	UIStringIDTableBucket** table;
	UIStringIDTableBucket* buckets;
	unsigned hashMask;
	unsigned count;
}
-(id)initWithKeysTransferingOwnership:(id*)keysTransferingOwnership count:(unsigned)count;
-(void)dealloc;
-(BOOL)lookupKey:(id)key identifier:(int*)identifier;
-(int)count;
@end

