/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import <Foundation/NSCoder.h>

@class UINibStringIDTable;

__attribute__((visibility("hidden")))
@interface UINibDecoder : NSCoder {
@private
	Class arrayClass;
	Class setClass;
	Class dictionaryClass;
	Class* classes;
	NSString** missingClasses;
	UINibDecoderObjectEntry* objects;
	UINibDecoderValue* values;
	char* valueTypes;
	void* valueData;
	unsigned valueDataSize;
	UINibDecoderHeader header;
	id* objectsByObjectID;
	unsigned* longObjectClassIDs;
	char* shortObjectClassIDs;
	unsigned* keyMasks;
	int inlinedValueKey;
	UINibDecoderRecursiveState recursiveState;
	UINibStringIDTable* keyIDTable;
	id delegate;
	UIKeyToKeyIDCache keyIDCache;
	UIKeyAndScopeToValueCache valueCache;
	int lookupRounds;
	int maxPossibleLookupRounds;
	int failedByKeyMask;
	int savedByKeyMask;
}
@property(assign) id delegate;
+(id)unarchiveObjectWithData:(id)data;
+(id)unarchiveObjectWithFile:(id)file;
-(id)initForReadingWithData:(id)data error:(id*)error;
-(id)initForReadingWithData:(id)data;
-(void)dealloc;
-(BOOL)validateAndIndexData:(id)data error:(id*)error;
-(BOOL)validateAndIndexClasses:(const void*)classes length:(unsigned long)length;
-(BOOL)validateAndIndexObjects:(const void*)objects length:(unsigned long)length;
-(BOOL)validateAndIndexValues:(const void*)values length:(unsigned long)length;
-(BOOL)validateAndIndexKeys:(const void*)keys length:(unsigned long)length;
-(id)nextGenericKey;
-(void)replaceObject:(id)object withObject:(id)object2;
-(BOOL)allowsKeyedCoding;
-(BOOL)containsValueForKey:(id)key;
-(id)decodeObjectForKey:(id)key;
-(const char*)decodeBytesForKey:(id)key returnedLength:(unsigned*)length;
-(BOOL)decodeBoolForKey:(id)key;
-(float)decodeFloatForKey:(id)key;
-(double)decodeDoubleForKey:(id)key;
-(long long)decodeInt64ForKey:(id)key;
-(int)decodeIntegerForKey:(id)key;
-(int)decodeIntForKey:(id)key;
-(int)decodeInt32ForKey:(id)key;
-(BOOL)decodeArrayOfFloats:(float*)floats count:(int)count forKey:(id)key;
-(BOOL)decodeArrayOfDoubles:(double*)doubles count:(int)count forKey:(id)key;
-(BOOL)decodeArrayOfCGFloats:(float*)cgfloats count:(int)count forKey:(id)key;
-(CGPoint)decodeCGPointForKey:(id)key;
-(CGSize)decodeCGSizeForKey:(id)key;
-(CGRect)decodeCGRectForKey:(id)key;
-(CGAffineTransform)decodeCGAffineTransformForKey:(id)key;
-(UIEdgeInsets)decodeUIEdgeInsetsForKey:(id)key;
-(void)decodeValueOfObjCType:(const char*)objCType at:(void*)at;
-(id)decodeNXObject;
-(id)decodeDataObject;
-(id)decodeObject;
-(id)decodePropertyList;
-(void)decodeValuesOfObjCTypes:(const char*)objCTypes;
-(void)decodeArrayOfObjCType:(const char*)objCType count:(unsigned)count at:(void*)at;
-(void*)decodeBytesWithReturnedLength:(unsigned*)returnedLength;
-(unsigned)systemVersion;
-(int)versionForClassName:(id)className;
-(void)finishDecoding;
@end

