/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIControl.h"
#import "UIPageControl.h"

@class NSMutableArray;

@interface UIPageControl : UIControl {
@private
	NSMutableArray* _indicators;
	int _currentPage;
	int _displayedPage;
	struct {
		unsigned hideForSinglePage : 1;
		unsigned defersCurrentPageDisplay : 1;
	} _pageControlFlags;
}
@property(assign, nonatomic) int numberOfPages;
@property(assign, nonatomic) int currentPage;
@property(assign, nonatomic) BOOL hidesForSinglePage;
@property(assign, nonatomic) BOOL defersCurrentPageDisplay;
-(void)_commonPageControlInit;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithCoder:(id)coder;
-(void)_populateArchivedSubviews:(id)subviews;
-(void)encodeWithCoder:(id)coder;
-(void)dealloc;
-(id)_pageIndicatorImageForPage:(int)page;
-(id)_pageIndicatorCurrentImageForPage:(int)page;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)layoutSubviews;
-(void)endTrackingAt:(CGPoint)at previous:(CGPoint)previous withEvent:(GSEventRef)event;
-(void)endTrackingWithTouch:(id)touch withEvent:(id)event;
-(void)updateCurrentPageDisplay;
-(CGSize)sizeForNumberOfPages:(int)pages;
@end

@interface UIPageControl (Internal)
-(void)_setDisplayedPage:(int)page;
-(int)_displayedPage;
-(void)_setCurrentPage:(int)page;
-(void)_updateCurrentPageDisplay;
@end

@interface UIPageControl (UIKitAccessibilityInterfaceBuilderSupport)
-(BOOL)isElementAccessibilityExposedToInterfaceBuilder;
@end

