/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>
#import "UIPasteboard.h"

@class UIColor, NSArray, NSString, UIImage, NSURL;

@interface UIPasteboard : NSObject {
@private
	NSString* _name;
}
@property(copy, nonatomic) NSArray* items;
@property(readonly, assign, nonatomic) int numberOfItems;
@property(readonly, assign, nonatomic) int changeCount;
@property(assign, nonatomic, getter=isPersistent) BOOL persistent;
@property(readonly, assign, nonatomic) NSString* name;
+(id)generalPasteboard;
+(id)pasteboardWithName:(id)name create:(BOOL)create;
+(id)pasteboardWithUniqueName;
+(void)removePasteboardWithName:(id)name;
-(id)init;
-(void)dealloc;
-(id)pasteboardTypes;
-(BOOL)containsPasteboardTypes:(id)types;
-(id)dataForPasteboardType:(id)pasteboardType;
-(id)valueForPasteboardType:(id)pasteboardType;
-(void)setValue:(id)value forPasteboardType:(id)pasteboardType;
-(void)setData:(id)data forPasteboardType:(id)pasteboardType;
-(id)pasteboardTypesForItemSet:(id)itemSet;
-(BOOL)containsPasteboardTypes:(id)types inItemSet:(id)itemSet;
-(id)itemSetWithPasteboardTypes:(id)pasteboardTypes;
-(id)valuesForPasteboardType:(id)pasteboardType inItemSet:(id)itemSet;
-(id)dataForPasteboardType:(id)pasteboardType inItemSet:(id)itemSet;
-(void)addItems:(id)items;
@end

@interface UIPasteboard (Static)
+(id)_findPasteboard;
-(id)_initWithName:(id)name system:(BOOL)system create:(BOOL)create;
-(void)_pasteboardChanged:(id)changed;
@end

@interface UIPasteboard (UIPasteboardDataExtensions)
@property(copy, nonatomic) NSArray* colors;
@property(copy, nonatomic) UIColor* color;
@property(copy, nonatomic) NSArray* images;
@property(copy, nonatomic) UIImage* image;
@property(copy, nonatomic) NSArray* URLs;
@property(copy, nonatomic) NSURL* URL;
@property(copy, nonatomic) NSArray* strings;
@property(copy, nonatomic) NSString* string;
@end

