/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import <Foundation/NSObject.h>

@class DOMNode, UIView;
@protocol UIFormPeripheral;

__attribute__((visibility("hidden")))
@interface UIPeripheralTransition : NSObject {
@private
	DOMNode* _nextNode;
	UIView<UIFormPeripheral>* _nextPeripheral;
}
@property(retain, nonatomic) DOMNode* _nextNode;
@property(retain, nonatomic) UIView<UIFormPeripheral>* _nextPeripheral;
-(id)initWithNode:(id)node withPeripheral:(id)peripheral;
-(void)dealloc;
-(id)completeWithCurrentPeripheral:(id)currentPeripheral;
-(CGRect)frame;
@end

