/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIAnimation.h"
#import "UIKit-Structs.h"


__attribute__((visibility("hidden")))
@interface UIPickerScrollAnimation : UIAnimation {
@private
	float _initialDuration;
	CGPoint _originalOffset;
	CGPoint _targetOffset;
}
-(CGPoint)targetOffset;
-(void)setTargetOffset:(CGPoint)offset;
-(void)setOriginalOffset:(CGPoint)offset;
-(void)setProgress:(float)progress;
-(float)initialDuration;
-(void)setInitialDuration:(float)duration;
@end

