/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "NSObject.h"


@protocol UIPickerViewDataSource <NSObject>
-(int)numberOfComponentsInPickerView:(id)pickerView;
-(int)pickerView:(id)view numberOfRowsInComponent:(int)component;
@end

