/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIImageAndTextTableCell.h"


@interface UIPickerTableCell : UIImageAndTextTableCell {
@private
	unsigned _checked : 1;
	unsigned _reserved : 31;
}
-(id)initWithFrame:(CGRect)frame;
-(void)updateHighlightColors;
-(void)setChecked:(BOOL)checked;
-(void)layoutSubviews;
-(BOOL)isChecked;
@end

