/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIPreferencesTableCell.h"
#import "UIKit-Structs.h"

@class UIControl;

@interface UIPreferencesControlTableCell : UIPreferencesTableCell {
@private
	UIControl* _control;
}
-(void)setControl:(id)control;
-(id)control;
-(void)_controlClicked:(id)clicked;
-(void)setUserInteractionEnabled:(BOOL)enabled;
@end

