/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIProgressView.h"


@interface UIProgressBar : UIProgressView {
}
@property(assign, nonatomic) int progressBarStyle;
-(id)initWithFrame:(CGRect)frame;
-(void)setStyle:(int)style;
@end

