/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import <Foundation/NSObject.h>
#import "NSCoding.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface UIProxyObject : NSObject <NSCoding> {
@private
	NSString* proxiedObjectIdentifier;
}
+(CFDictionaryRef)proxyDecodingMap;
+(void)addMappingFromIdentifier:(id)identifier toObject:(id)object forCoder:(id)coder;
+(void)addMappings:(id)mappings forCoder:(id)coder;
+(id)mappedObjectForCoder:(id)coder withIdentifier:(id)identifier;
+(void)removeMappingsForCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)dealloc;
-(void)setProxiedObjectIdentifier:(id)identifier;
-(id)proxiedObjectIdentifier;
@end

