/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIRemoveControl.h"


__attribute__((visibility("hidden")))
@interface UIPreferencesTableCellRemoveControl : UIRemoveControl {
}
-(void)addConfirmationButtonSubview:(id)subview withWidth:(float)width target:(id)target;
-(float)removeButtonAnimationDuration;
-(CGRect)removeButtonEndingFrame;
-(CGRect)removeButtonStartingFrame;
-(float)_verticalOffsetFromTarget;
-(float)_removeConfirmationButtonVerticalOffset;
-(CGRect)targetContentBounds;
@end

