/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIActivityIndicatorView.h"


@interface UIProgressIndicator : UIActivityIndicatorView {
}
@property(assign, nonatomic) int progressIndicatorStyle;
+(CGSize)size;
-(void)setStyle:(int)style;
-(void)setAnimating:(BOOL)animating;
-(void)startAnimation;
-(void)stopAnimation;
@end

