/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>
#import "UIResponder.h"
#import "UIKit-Structs.h"

@class NSUndoManager;

@interface UIResponder : NSObject {
}
@property(readonly, assign, nonatomic) NSUndoManager* undoManager;
-(void)mouseDown:(GSEventRef)down;
-(void)mouseUp:(GSEventRef)up;
-(void)mouseDragged:(GSEventRef)dragged;
-(void)mouseEntered:(GSEventRef)entered;
-(void)mouseExited:(GSEventRef)exited;
-(void)mouseMoved:(GSEventRef)moved;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(void)motionBegan:(int)began withEvent:(id)event;
-(void)motionEnded:(int)ended withEvent:(id)event;
-(void)motionCancelled:(int)cancelled withEvent:(id)event;
-(void)scrollWheel:(GSEventRef)wheel;
-(void)keyDown:(GSEventRef)down;
-(void)keyUp:(GSEventRef)up;
-(void)gestureStarted:(GSEventRef)started;
-(void)gestureEnded:(GSEventRef)ended;
-(void)gestureChanged:(GSEventRef)changed;
-(id)nextResponder;
-(BOOL)_containedInAbsoluteResponderChain;
-(BOOL)_containsResponder:(id)responder;
-(BOOL)becomeFirstResponder;
-(BOOL)canBecomeFirstResponder;
-(BOOL)resignFirstResponder;
-(BOOL)canResignFirstResponder;
-(BOOL)isFirstResponder;
-(id)firstResponder;
-(void)_clearBecomeFirstResponderWhenCapable;
-(BOOL)canPerformAction:(SEL)action withSender:(id)sender;
@end

@interface UIResponder (Static)
-(void)_setFirstResponder:(id)responder;
-(id)_firstResponder;
-(id)_responderForBecomeFirstResponder;
-(BOOL)_becomeFirstResponderWhenPossible;
@end

@interface UIResponder (Internal)
-(void)_controlMouseDown:(GSEventRef)down;
-(void)_controlMouseUp:(GSEventRef)up;
-(void)_controlMouseDragged:(GSEventRef)dragged;
-(void)_controlTouchBegan:(id)began withEvent:(id)event;
-(void)_controlTouchMoved:(id)moved withEvent:(id)event;
-(void)_controlTouchEnded:(id)ended withEvent:(id)event;
-(id)_targetForAction:(SEL)action withSender:(id)sender;
@end

