/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIControl.h"


__attribute__((visibility("hidden")))
@interface UIRemoveControlMinusButton : UIControl {
@private
	unsigned _rotated : 1;
	unsigned _rotating : 1;
	unsigned _hiding : 1;
	unsigned _showAsPlus : 1;
	unsigned _reserved : 28;
	float _verticalOffset;
}
+(float)defaultWidth;
+(id)minusImage;
+(id)plusImage;
-(id)initWithRemoveControl:(id)removeControl;
-(void)dealloc;
-(void)setHiding:(BOOL)hiding;
-(BOOL)isHiding;
-(void)drawRect:(CGRect)rect;
-(void)animator:(id)animator stopAnimation:(id)animation;
-(void)toggleRotate:(BOOL)rotate;
-(BOOL)isRotated;
-(BOOL)isRotating;
-(void)_toggleRotateAnimationDidStop:(id)_toggleRotateAnimation finished:(BOOL)finished;
@end

