/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIButton.h"
#import "UIKit-Structs.h"

@class UIBezierPath;

__attribute__((visibility("hidden")))
@interface UIRoundedRectButton : UIButton {
@private
	UIBezierPath* _fillPath;
}
-(void)_commonRoundedRectButtonInit;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)_invalidatePaths;
-(void)setFrame:(CGRect)frame;
-(CGSize)sizeThatFits:(CGSize)fits;
-(int)buttonType;
-(void)setHighlighted:(BOOL)highlighted;
-(void)drawRect:(CGRect)rect;
@end

