/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>

@class NSString, NSNumber;

__attribute__((visibility("hidden")))
@interface UIRuntimeAccessibilityConfiguration : NSObject {
@private
	NSString* accessibilityConfigurationHint;
	NSString* accessibilityConfigurationLabel;
	NSNumber* accessibilityConfigurationTraits;
	NSNumber* isAccessibilityConfigurationElement;
	NSObject* object;
}
@property(retain, nonatomic) NSString* accessibilityConfigurationHint;
@property(retain, nonatomic) NSString* accessibilityConfigurationLabel;
@property(retain, nonatomic) NSNumber* accessibilityConfigurationTraits;
@property(retain, nonatomic) NSNumber* isAccessibilityConfigurationElement;
@property(retain, nonatomic) NSObject* object;
-(id)initWithObject:(id)object label:(id)label hint:(id)hint traits:(id)traits andIsAccessibilityElement:(id)element;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)dealloc;
-(void)applyConfiguration;
@end

