/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIGestureRecognizer.h"

@class UIDelayedAction;

__attribute__((visibility("hidden")))
@interface UIScrollViewDelayedTouchesBeganGestureRecognizer : UIGestureRecognizer {
@private
	UIDelayedAction* _touchDelay;
}
-(void)clearTimer;
-(void)sendTouchesShouldBeginForTouches:(id)sendTouches withEvent:(id)event;
-(void)sendTouchesShouldBeginForDelayedTouches:(id)sendTouches;
-(void)enoughTimeElapsed:(id)elapsed;
-(void)dealloc;
-(void)reset;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(BOOL)_shouldSaveGestureFromExclusion:(id)exclusion;
@end

