/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIView.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface UIScrubberTimeView : UIView {
@private
	NSString* _time;
	unsigned _align : 2;
}
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)setTime:(id)time;
-(id)time;
-(void)drawRect:(CGRect)rect;
@end

