/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIView.h"


__attribute__((visibility("hidden")))
@interface UIScrollerIndicator : UIView {
@private
	int _style;
}
-(id)initInScroller:(id)scroller style:(int)style;
-(void)drawRect:(CGRect)rect;
@end

