/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIAnimation.h"
#import "UIKit-Structs.h"


@interface UIScrollAnimation : UIAnimation {
	CGPoint _startPoint;
	CGPoint _endPoint;
}
-(void)setStartPoint:(CGPoint)point;
-(void)setEndPoint:(CGPoint)point;
-(void)setProgress:(float)progress;
@end

