/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIView.h"

@class NSMutableArray, UISectionIndex, UISectionTable, NSSet;

@interface UISectionList : UIView {
	UISectionTable* _table;
	UISectionIndex* _index;
	NSMutableArray* _titles;
	NSSet* _indexTitlesAsSet;
	int _sectionCount;
	float _listWidth;
	struct {
		unsigned isTranslucent : 1;
	} _sectionListFlags;
}
+(float)defaultIndexWidth;
-(id)initWithFrame:(CGRect)frame showSectionIndex:(BOOL)index;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)setDataSource:(id)source;
-(float)marginForIndexControl:(BOOL)indexControl;
-(id)allTitles;
-(void)_languageChanged;
-(id)indexTitles;
-(void)setAllowsScrollIndicators:(BOOL)indicators;
-(void)setShouldHideHeaderInShortLists:(BOOL)hideHeaderInShortLists;
-(BOOL)showsSectionHeaders;
-(BOOL)showsSectionIndex;
-(void)setNonIndexedTitlesShownLast:(BOOL)last;
-(void)setSectionListStyle:(int)style;
-(void)noteIndexTitlesDidChange;
-(void)reloadData;
-(int)numberOfSections;
-(id)titleForSection:(int)section;
-(int)closestSectionForTitle:(id)title;
-(id)_indexTitlesAsSet;
-(void)_setIndexVisible:(BOOL)visible;
-(id)table;
@end

