/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UITableView.h"
#import "UIKit-Structs.h"

@class UISearchDisplayController;

__attribute__((visibility("hidden")))
@interface UISearchResultsTableView : UITableView {
@private
	UISearchDisplayController* _controller;
}
@property(assign, nonatomic) UISearchDisplayController* controller;
-(void)setContentOffset:(CGPoint)offset;
-(void)noteNumberOfRowsChanged;
-(float)_offsetForNoResultsMessage;
@end

