/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>
#import "UIKit-Structs.h"

@class UIView, UILabel, UITableView, NSString, UIViewController, UISearchBar;
@protocol UISearchDisplayDelegate, UITableViewDelegate, UITableViewDataSource;

@interface UISearchDisplayController : NSObject {
@private
	UIViewController* _viewController;
	UITableView* _tableView;
	UIView* _dimmingView;
	UISearchBar* _searchBar;
	UILabel* _noResultsLabel;
	NSString* _noResultsMessage;
	id<UISearchDisplayDelegate> _delegate;
	id<UITableViewDataSource> _tableViewDataSource;
	id<UITableViewDelegate> _tableViewDelegate;
	CFArrayRef _containingScrollViews;
	float _lastKeyboardAdjustment;
	struct {
		unsigned pushedRunLoop : 1;
		unsigned isRotatingRight : 1;
		unsigned isZoomRubberBandEnabled : 1;
		unsigned zoomsFromCurrentToMinOrMax : 1;
		unsigned updatesScroller : 1;
		unsigned isAnimatingZoomFailure : 1;
	} _searchDisplayControllerFlags;
}
@property(assign, nonatomic) id<UISearchDisplayDelegate> delegate;
@property(readonly, assign, nonatomic) UIViewController* searchContentsController;
@property(readonly, assign, nonatomic) UISearchBar* searchBar;
@property(assign, nonatomic) id<UITableViewDataSource> searchResultsDataSource;
@property(assign, nonatomic) id<UITableViewDelegate> searchResultsDelegate;
@property(readonly, assign, nonatomic) UITableView* searchResultsTableView;
@property(copy, nonatomic) NSString* noResultsMessage;
@property(assign, nonatomic) BOOL automaticallyShowsNoResultsMessage;
@property(assign, nonatomic) BOOL noResultsMessageVisible;
@property(assign, nonatomic, getter=isActive) BOOL active;
-(id)init;
-(id)initWithSearchBar:(id)searchBar contentsController:(id)controller;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)dealloc;
-(void)_configureSearchBarForTableView;
-(void)_cleanUpSearchBar;
-(void)_configureNewSearchBar;
-(void)setSearchBar:(id)bar;
-(void)setSearchContentsController:(id)controller;
-(id)_containingViewOfClass:(Class)aClass;
-(id)_containingTableView;
-(void)_destroyManagedTableView;
-(void)_disableParentScrollViews;
-(void)_enableParentScrollViews;
-(CGRect)_tableViewFrame;
-(void)_setTableViewVisible:(BOOL)visible inView:(id)view;
-(void)_updateSearchBarForTableViewIndexBar:(id)tableViewIndexBar;
-(void)_indexBarFrameChanged:(id)changed;
-(void)_searchBarSuperviewWillChange;
-(void)_searchBarSuperviewChanged;
-(void)showHideAnimationDidFinish;
-(void)setActive:(BOOL)active animated:(BOOL)animated;
-(void)_keyboardWillShow:(id)_keyboard;
-(void)_keyboardWillHide:(id)_keyboard;
-(void)windowWillAnimateRotation:(id)window;
-(void)windowDidRotate:(id)window;
-(void)searchBarTextDidBeginEditing:(id)searchBarText;
-(void)searchBarCancelButtonClicked:(id)clicked;
-(void)searchBarSearchButtonClicked:(id)clicked;
-(void)searchBar:(id)bar textDidChange:(id)text;
-(void)searchBar:(id)bar selectedScopeButtonIndexDidChange:(int)selectedScopeButtonIndex;
-(void)navigationControllerWillShowViewController:(id)navigationController;
-(void)navigationControllerDidShowViewController:(id)navigationController;
-(void)_updateNoSearchResultsMessageVisiblity;
-(void)_managedTableViewDidScroll;
-(void)_clearViewController;
@end

