/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */



@protocol UISelectedItemPrivate
-(id)node;
-(BOOL)selected;
-(void)setSelected:(BOOL)selected;
-(void)unselect;
@end

