/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIView.h"

@class UIImage;

__attribute__((visibility("hidden")))
@interface UISelectionIndicatorView : UIView {
@private
	UIImage* _image;
	XXStruct_4cr1oD _slices;
}
-(id)initWithFrame:(CGRect)frame withImageName:(id)imageName;
-(void)dealloc;
-(void)setFrame:(CGRect)frame;
-(void)drawRect:(CGRect)rect;
@end

