/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UITextTapRecognizer.h"

@class UIView;
@protocol UITextSelectingContent;

__attribute__((visibility("hidden")))
@interface UISelectionTapRecognizer : UITextTapRecognizer {
@private
	UIView<UITextSelectingContent>* _textView;
}
@property(assign) UIView<UITextSelectingContent>* textView;
-(BOOL)isCloseToSelection;
-(void)setState:(int)state;
@end

