/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIView.h"

@class UIColor, UIImage;

__attribute__((visibility("hidden")))
@interface UISearchBarBackground : UIView {
@private
	UIColor* _tintColor;
	UIImage* _backgroundImage;
	unsigned _barStyle : 3;
	unsigned _isTranslucent : 1;
	unsigned _usesEmbeddedAppearance : 1;
}
@property(retain, nonatomic) UIColor* tintColor;
@property(retain, nonatomic) UIImage* backgroundImage;
@property(assign, nonatomic) BOOL usesEmbeddedAppearance;
@property(assign, nonatomic, getter=isTranslucent) BOOL translucent;
@property(assign, nonatomic) int barStyle;
-(void)dealloc;
-(BOOL)_canDrawContent;
-(void)drawRect:(CGRect)rect;
@end

