/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UILabel.h"


__attribute__((visibility("hidden")))
@interface UISegmentLabel : UILabel {
@private
	int _style;
}
-(id)initWithSegmentedControlStyle:(int)segmentedControlStyle;
-(id)_disabledFontColor;
@end

