/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIControl.h"
#import "NSCoding.h"
#import "UISlider.h"

@class UIImageView, UIImage;

@interface UISlider : UIControl <NSCoding> {
@private
	float _value;
	float _minValue;
	float _maxValue;
	CFDictionaryRef _contentLookup;
	UIImageView* _minValueImageView;
	UIImageView* _maxValueImageView;
	UIImageView* _thumbView;
	UIImageView* _minTrackView;
	UIImageView* _maxTrackView;
	struct {
		unsigned pushedRunLoop : 1;
		unsigned isRotatingRight : 1;
		unsigned isZoomRubberBandEnabled : 1;
		unsigned zoomsFromCurrentToMinOrMax : 1;
		unsigned updatesScroller : 1;
		unsigned isAnimatingZoomFailure : 1;
	} _sliderFlags;
	float _hitOffset;
}
@property(assign, nonatomic) float value;
@property(assign, nonatomic) float minimumValue;
@property(assign, nonatomic) float maximumValue;
@property(readonly, assign, nonatomic) UIImage* currentMaximumTrackImage;
@property(readonly, assign, nonatomic) UIImage* currentMinimumTrackImage;
@property(readonly, assign, nonatomic) UIImage* currentThumbImage;
@property(assign, nonatomic, getter=isContinuous) BOOL continuous;
@property(retain, nonatomic) UIImage* maximumValueImage;
@property(retain, nonatomic) UIImage* minimumValueImage;
-(id)init;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithCoder:(id)coder;
-(void)_populateArchivedSubviews:(id)subviews;
-(void)encodeWithCoder:(id)coder;
-(void)_initImages;
-(void)_initSubviews;
-(void)dealloc;
-(void)setThumbImage:(id)image forState:(unsigned)state;
-(void)setMinimumTrackImage:(id)image forState:(unsigned)state;
-(void)setMaximumTrackImage:(id)image forState:(unsigned)state;
-(id)thumbImageForState:(unsigned)state;
-(id)minimumTrackImageForState:(unsigned)state;
-(id)maximumTrackImageForState:(unsigned)state;
-(CGRect)minimumValueImageRectForBounds:(CGRect)bounds;
-(CGRect)maximumValueImageRectForBounds:(CGRect)bounds;
-(CGRect)trackRectForBounds:(CGRect)bounds;
-(CGRect)thumbRectForBounds:(CGRect)bounds trackRect:(CGRect)rect value:(float)value;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)setFrame:(CGRect)frame;
-(void)setBounds:(CGRect)bounds;
-(void)layoutSubviews;
-(void)_layoutSubviewsForBoundsChange:(BOOL)boundsChange;
-(void)_updateAppearanceForEnabled:(BOOL)enabled;
-(void)setEnabled:(BOOL)enabled;
-(void)setHighlighted:(BOOL)highlighted;
-(void)setSelected:(BOOL)selected;
-(void)setValue:(float)value animated:(BOOL)animated;
-(void)_setValue:(float)value andSendAction:(BOOL)action;
-(void)_sliderAnimationWillStart:(id)_sliderAnimation context:(void*)context;
-(void)_sliderAnimationDidStop:(id)_sliderAnimation finished:(id)finished context:(void*)context;
-(void)_sendDelayedActions;
-(BOOL)beginTrackingAt:(CGPoint)at withEvent:(GSEventRef)event;
-(BOOL)continueTrackingAt:(CGPoint)at previous:(CGPoint)previous withEvent:(GSEventRef)event;
-(void)endTrackingAt:(CGPoint)at previous:(CGPoint)previous withEvent:(GSEventRef)event;
-(BOOL)cancelMouseTracking;
-(void)_controlMouseDown:(GSEventRef)down;
-(void)_controlMouseUp:(GSEventRef)up;
-(void)_controlMouseDragged:(GSEventRef)dragged;
-(BOOL)beginTrackingWithTouch:(id)touch withEvent:(id)event;
-(BOOL)continueTrackingWithTouch:(id)touch withEvent:(id)event;
-(void)endTrackingWithTouch:(id)touch withEvent:(id)event;
-(void)_controlTouchBegan:(id)began withEvent:(id)event;
-(void)_controlTouchMoved:(id)moved withEvent:(id)event;
-(void)_controlTouchEnded:(id)ended withEvent:(id)event;
-(BOOL)cancelTouchTracking;
@end

@interface UISlider (SyntheticEvents)
-(id)_scriptingInfo;
-(id)scriptingInfoWithChildren;
@end

@interface UISlider (UISliderContentLookup)
-(void)_setContent:(id)content forState:(unsigned)state;
-(void)_setThumbImage:(id)image forStates:(unsigned)states;
-(void)_setMinimumTrackImage:(id)image forStates:(unsigned)states;
-(void)_setMaximumTrackImage:(id)image forStates:(unsigned)states;
-(id)_contentForState:(unsigned)state;
-(id)_thumbImageForState:(unsigned)state;
-(id)_minimumTrackImageForState:(unsigned)state;
-(id)_maximumTrackImageForState:(unsigned)state;
@end

@interface UISlider (UISliderPrivate)
-(BOOL)_alwaysHandleScrollerMouseEvent;
-(BOOL)isAnimatingValueChange;
-(void)setShowValue:(BOOL)value;
-(CGRect)valueTextRectForBounds:(CGRect)bounds;
-(id)createThumbView;
-(void)setThumbImage:(id)image forStates:(unsigned)states;
-(void)setMinimumTrackImage:(id)image forStates:(unsigned)states;
-(void)setMaximumTrackImage:(id)image forStates:(unsigned)states;
-(void)_setTrackEnabled:(BOOL)enabled;
-(BOOL)_trackEnabled;
-(void)_setThumbEnabled:(BOOL)enabled;
-(BOOL)_isThumbEnabled;
@end

@interface UISlider (UIKitAccessibilityInterfaceBuilderSupport)
-(BOOL)isAccessibilityElementByDefault;
-(BOOL)isElementAccessibilityExposedToInterfaceBuilder;
@end

