/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>

@class UIImage;

__attribute__((visibility("hidden")))
@interface UISliderContent : NSObject {
@private
	UIImage* thumb;
	UIImage* minTrack;
	UIImage* maxTrack;
}
@property(retain, nonatomic) UIImage* thumb;
@property(retain, nonatomic) UIImage* minTrack;
@property(retain, nonatomic) UIImage* maxTrack;
@property(readonly, assign, nonatomic) BOOL isEmpty;
-(void)dealloc;
@end

