/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIViewController.h"


__attribute__((visibility("hidden")))
@interface UISnapshotModalViewController : UIViewController {
@private
	int _interfaceOrientation;
	UIViewController* _disappearingViewController;
}
@property(retain, nonatomic) UIViewController* disappearingViewController;
-(id)initWithInterfaceOrientation:(int)interfaceOrientation;
-(void)dealloc;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidDisappear:(BOOL)view;
-(BOOL)_isSupportedInterfaceOrientation:(int)orientation;
@end

