/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>
#import "UIModalViewDelegate.h"

@class UIModalView;

__attribute__((visibility("hidden")))
@interface UISystemAlertRequest : NSObject <UIModalViewDelegate> {
@private
	int _alertID;
	UIModalView* _sheet;
	id _target;
	SEL _action;
}
-(id)initWithAlertID:(int)alertID sheet:(id)sheet target:(id)target action:(SEL)action;
-(void)dealloc;
-(void)alertSheet:(id)sheet buttonClicked:(int)clicked;
@end

