/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIControl.h"
#import "UITabBarButton.h"

@class UILabel, UITabBarButtonBadge, UITabBarSelectionIndicatorView;

__attribute__((visibility("hidden")))
@interface UITabBarButton : UIControl {
@private
	CGRect _hitRect;
	UIView* _info;
	UILabel* _label;
	UITabBarButtonBadge* _badge;
	UITabBarSelectionIndicatorView* _selectedIndicator;
	BOOL _onState;
	BOOL _barHeight;
	BOOL _badgeAnimated;
	UIEdgeInsets _infoInsets;
}
+(id)_defaultLabelFont;
+(id)_defaultLabelColor;
+(id)_donePushButton;
-(id)initWithImage:(id)image selectedImage:(id)image2 label:(id)label withInsets:(UIEdgeInsets)insets;
-(void)dealloc;
-(void)setImage:(id)image;
-(void)_setTabBarHitRect:(CGRect)rect;
-(CGRect)_tabBarHitRect;
-(void)_showSelectedIndicator:(BOOL)indicator changeSelection:(BOOL)selection;
-(void)_setSelected:(BOOL)selected;
-(void)_positionBadge;
-(void)setFrame:(CGRect)frame;
-(void)_setBadgeValue:(id)value;
-(void)_badgeAnimationDidStop:(id)_badgeAnimation finished:(id)finished;
-(void)_setBadgeAnimated:(BOOL)animated;
-(void)setEnabled:(BOOL)enabled;
-(BOOL)pointInside:(CGPoint)inside forEvent:(GSEventRef)event;
-(BOOL)pointInside:(CGPoint)inside withEvent:(id)event;
-(void)layoutSubviews;
-(void)_setOn:(BOOL)on;
-(BOOL)_isOn;
-(void)_setBarHeight:(float)height;
-(BOOL)_useBarHeight;
@end

@interface UITabBarButton (SynthEvents)
-(id)_scriptingInfo;
@end

