/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIRemoveControl.h"


__attribute__((visibility("hidden")))
@interface UITableCellRemoveControl : UIRemoveControl {
@private
	float _verticalOffset;
}
-(id)initWithTarget:(id)target;
-(float)_verticalOffsetFromTarget;
@end

