/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>

@class UITabBarItem, UIImageView;

__attribute__((visibility("hidden")))
@interface UITabBarItemProxy : NSObject {
@private
	UITabBarItem* _item;
	UIImageView* _view;
}
-(id)initWithItem:(id)item inTabBar:(id)tabBar;
-(void)dealloc;
-(id)item;
-(id)view;
@end

