/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIControl.h"
#import "UITableViewCellEditControl.h"

@class UITableViewCell;

__attribute__((visibility("hidden")))
@interface UITableViewCellEditControl : UIControl {
@private
	UITableViewCell* _cell;
	unsigned _style : 2;
	unsigned _rotated : 1;
	unsigned _rotating : 1;
	unsigned _hiding : 1;
	unsigned _reserved : 27;
}
@property(assign, nonatomic, getter=isHiding) BOOL hiding;
@property(assign, nonatomic, getter=isRotated) BOOL rotated;
+(CGSize)defaultSize;
-(id)initWithTableViewCell:(id)tableViewCell editingStyle:(int)style;
-(void)layoutSubviews;
-(void)setFrame:(CGRect)frame;
-(void)setHighlighted:(BOOL)highlighted;
-(void)setSelected:(BOOL)selected;
-(void)setRotated:(BOOL)rotated animated:(BOOL)animated;
-(BOOL)isRotating;
-(void)_toggleRotateAnimationDidStop:(id)_toggleRotateAnimation finished:(BOOL)finished;
-(void)_multiselectColorChanged;
@end

@interface UITableViewCellEditControl (UITableViewCellEditControlStatic)
+(id)_minusImage;
+(id)_plusImage;
+(id)_multiSelectNotSelectedImage;
+(id)_multiSelectSelectedImage;
+(id)_multiSelectHighlightedImage;
-(void)_toggleRotate;
-(id)_currentImage;
@end

