/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIView.h"

@class UIImage;

__attribute__((visibility("hidden")))
@interface UITabBarBadgeBackground : UIView {
@private
	UIImage* _image;
}
-(id)initWithImage:(id)image;
-(void)dealloc;
-(void)drawRect:(CGRect)rect;
@end

