/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIBarItem.h"
#import "UITabBarItem.h"

@class NSString, UIView, UIImage, NSSet;

@interface UITabBarItem : UIBarItem {
@private
	NSString* _title;
	NSSet* _possibleTitles;
	SEL _action;
	id _target;
	UIImage* _image;
	UIImage* _selectedImage;
	UIImage* _unselectedImage;
	UIEdgeInsets _imageInsets;
	NSString* _badgeValue;
	UIView* _view;
	int _tag;
	struct {
		unsigned enabled : 1;
		unsigned style : 3;
		unsigned isSystemItem : 1;
		unsigned systemItem : 7;
		unsigned viewIsCustom : 1;
		unsigned animatedBadge : 1;
		unsigned customSelectedImage : 1;
		unsigned customUnselectedImage : 1;
	} _tabBarItemFlags;
}
@property(assign, nonatomic) int tag;
@property(copy, nonatomic) NSString* badgeValue;
-(id)init;
-(id)initWithTitle:(id)title image:(id)image tag:(int)tag;
-(id)initWithTabBarSystemItem:(int)tabBarSystemItem tag:(int)tag;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)dealloc;
-(void)setEnabled:(BOOL)enabled;
-(BOOL)isEnabled;
-(void)setTitle:(id)title;
-(id)title;
-(void)setImage:(id)image;
-(id)image;
-(void)setImageInsets:(UIEdgeInsets)insets;
-(UIEdgeInsets)imageInsets;
@end

@interface UITabBarItem (Static)
-(id)nextResponder;
-(id)_createViewForTabBar:(id)tabBar showingBadge:(BOOL)badge;
-(void)_updateView;
@end

@interface UITabBarItem (UITabBarItem_Private)
@property(assign, nonatomic) id target;
@property(assign, nonatomic) SEL action;
@property(retain, nonatomic) UIImage* unselectedImage;
@property(retain, nonatomic) UIImage* selectedImage;
@property(assign, nonatomic) BOOL animatedBadge;
@property(assign, nonatomic) BOOL viewIsCustom;
@property(retain, nonatomic) UIView* view;
-(BOOL)isSystemItem;
-(int)systemItem;
-(id)_internalTitle;
-(id)_internalTemplateImage;
@end

