/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>

@class UITableViewCellEditControl, UITableViewCellDeleteConfirmationControl, UITableViewCellReorderControl, UIView, UITableViewCell;

__attribute__((visibility("hidden")))
@interface UITableViewCellEditingData : NSObject {
@private
	UITableViewCell* _cell;
	int _editingStyle;
	UITableViewCellEditControl* _editControl;
	UITableViewCellReorderControl* _reorderControl;
	UITableViewCellDeleteConfirmationControl* _deleteConfirmationControl;
	UIView* _reorderSeparatorView;
}
@property(readonly, assign, nonatomic, getter=isDataRequired) BOOL dataRequired;
-(id)initWithTableViewCell:(id)tableViewCell editingStyle:(int)style;
-(void)dealloc;
-(id)editControl:(BOOL)control;
-(id)reorderControl:(BOOL)control;
-(id)deleteConfirmationControl:(BOOL)control;
-(id)reorderSeparatorView:(BOOL)view;
@end

