/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UILabel.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface UITableViewCountView : UILabel {
@private
	NSString* _countString;
	int _count;
}
-(id)initWithFrame:(CGRect)frame withCountString:(id)countString withCount:(int)count;
-(void)dealloc;
-(void)setCountString:(id)string withCount:(int)count;
-(void)setCount:(int)count;
-(int)count;
@end

