/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIAnimation.h"


__attribute__((visibility("hidden")))
@interface UITableCellFadeAnimation : UIAnimation {
@private
	BOOL _select;
}
-(id)initWithTarget:(id)target select:(BOOL)select;
-(void)dealloc;
-(void)_appSuspended:(id)suspended;
-(void)setProgress:(float)progress;
@end

