/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "NSCoding.h"
#import "UIView.h"
#import "UITableViewCell.h"

@class _UITableViewCellOldEditingData, NSString, UILabel, UIButton, UIImageView, UITextField, NSTimer, UIColor;

@interface UITableViewCell : UIView <NSCoding> {
@private
	id _layoutManager;
	id _target;
	SEL _editAction;
	SEL _accessoryAction;
	id _oldEditingData;
	id _editingData;
	float _rightMargin;
	int _indentationLevel;
	float _indentationWidth;
	NSString* _reuseIdentifier;
	UIView* _contentView;
	UIImageView* _imageView;
	UILabel* _textLabel;
	UILabel* _detailTextLabel;
	UIView* _backgroundView;
	UIView* _selectedBackgroundView;
	UIView* _selectedOverlayView;
	UIColor* _backgroundColor;
	UIColor* _separatorColor;
	UIView* _floatingSeparatorView;
	CFDictionaryRef _unhighlightedStates;
	struct {
		unsigned showingDeleteConfirmation : 1;
		unsigned separatorStyle : 3;
		unsigned selectionStyle : 3;
		unsigned selectionFadeFraction : 11;
		unsigned editing : 1;
		unsigned editingStyle : 3;
		unsigned accessoryType : 3;
		unsigned editingAccessoryType : 3;
		unsigned showsAccessoryWhenEditing : 1;
		unsigned showsReorderControl : 1;
		unsigned showDisclosure : 1;
		unsigned showTopSeparator : 1;
		unsigned disclosureClickable : 1;
		unsigned disclosureStyle : 1;
		unsigned showingRemoveControl : 1;
		unsigned sectionLocation : 3;
		unsigned tableViewStyle : 1;
		unsigned shouldIndentWhileEditing : 1;
		unsigned fontSet : 1;
		unsigned usingDefaultSelectedBackgroundView : 1;
		unsigned wasSwiped : 1;
		unsigned highlighted : 1;
		unsigned separatorDirty : 1;
		unsigned drawn : 1;
		unsigned drawingDisabled : 1;
		unsigned style : 12;
		unsigned showingMenu : 1;
	} _tableCellFlags;
	UIButton* _accessoryView;
	UIButton* _editingAccessoryView;
	UIView* _customAccessoryView;
	UIView* _customEditingAccessoryView;
	UIView* _separatorView;
	UIView* _topSeparatorView;
	UITextField* _editableTextField;
	double _lastSelectionTime;
	NSTimer* _deselectTimer;
	float _textFieldOffset;
	SEL _returnAction;
}
@property(readonly, assign, nonatomic) BOOL showingDeleteConfirmation;
@property(assign, nonatomic, getter=isEditing) BOOL editing;
@property(assign, nonatomic) float indentationWidth;
@property(assign, nonatomic) int indentationLevel;
@property(retain, nonatomic) UIView* editingAccessoryView;
@property(assign, nonatomic) int editingAccessoryType;
@property(retain, nonatomic) UIView* accessoryView;
@property(assign, nonatomic) int accessoryType;
@property(assign, nonatomic) BOOL shouldIndentWhileEditing;
@property(assign, nonatomic) BOOL showsReorderControl;
@property(readonly, assign, nonatomic) int editingStyle;
@property(assign, nonatomic, getter=isHighlighted) BOOL highlighted;
@property(assign, nonatomic, getter=isSelected) BOOL selected;
@property(assign, nonatomic) int selectionStyle;
@property(readonly, copy, nonatomic) NSString* reuseIdentifier;
@property(retain, nonatomic) UIView* selectedBackgroundView;
@property(retain, nonatomic) UIView* backgroundView;
@property(readonly, retain, nonatomic) UIView* contentView;
@property(readonly, retain, nonatomic) UILabel* detailTextLabel;
@property(readonly, retain, nonatomic) UILabel* textLabel;
@property(readonly, retain, nonatomic) UIImageView* imageView;
-(void)_updateSeparatorContent;
-(id)init;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithFrame:(CGRect)frame reuseIdentifier:(id)identifier;
-(void)_setupTableViewCellCommon;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
-(id)initWithCoder:(id)coder;
-(void)_populateArchivedSubviews:(id)subviews;
-(void)encodeWithCoder:(id)coder;
-(void)dealloc;
-(void)_didCreateContentView;
-(BOOL)drawingEnabled;
-(void)setDrawingEnabled:(BOOL)enabled;
-(BOOL)_canDrawContent;
-(void)setText:(id)text;
-(id)text;
-(void)_setFont:(id)font layout:(BOOL)layout;
-(void)setFont:(id)font;
-(id)font;
-(void)setTextAlignment:(int)alignment;
-(int)textAlignment;
-(void)setLineBreakMode:(int)mode;
-(int)lineBreakMode;
-(void)setTextColor:(id)color;
-(id)textColor;
-(void)setSelectedTextColor:(id)color;
-(id)selectedTextColor;
-(void)setImage:(id)image;
-(id)image;
-(void)setSelectedImage:(id)image;
-(id)selectedImage;
-(void)setSeparatorStyle:(int)style;
-(int)separatorStyle;
-(void)_setTableBackgroundCGColor:(CGColorRef)color;
-(id)_contentBackgroundColor;
-(void)setTableBackgroundColor:(id)color;
-(id)tableBackgroundColor;
-(void)setSeparatorColor:(id)color;
-(id)separatorColor;
-(void)setReuseIdentifier:(id)identifier;
-(void)prepareForReuse;
-(void)_saveOpaqueViewState:(id)state;
-(id)_multiselectBackgroundColor;
-(void)_setOpaque:(BOOL)opaque forSubview:(id)subview;
-(void)showSelectedBackgroundView:(BOOL)view animated:(BOOL)animated;
-(void)_cancelInternalPerformRequests;
-(void)setHighlighted:(BOOL)highlighted animated:(BOOL)animated;
-(void)_deselectAnimationFinished;
-(void)_delayedDeselect;
-(void)setSelected:(BOOL)selected animated:(BOOL)animated;
-(BOOL)isAtLeastHalfSelected;
-(float)selectionPercent;
-(BOOL)_isHighlighted;
-(void)_updateHighlightColors;
-(void)_drawContentInRect:(CGRect)rect selected:(BOOL)selected;
-(void)setLayoutManager:(id)manager;
-(id)layoutManager;
-(void)setEditingStyle:(int)style;
-(void)_syncAccessoryViewsIfNecessary;
-(void)setHidesAccessoryWhenEditing:(BOOL)editing;
-(BOOL)hidesAccessoryWhenEditing;
-(unsigned)currentStateMask;
-(void)setEditing:(BOOL)editing animated:(BOOL)animated;
-(void)setShowingDeleteConfirmation:(BOOL)confirmation;
-(CGRect)_delegateConfirmationRect;
-(CGRect)backgroundRectForBounds:(CGRect)bounds;
-(CGRect)contentRectForBounds:(CGRect)bounds;
-(CGRect)textRectForContentRect:(CGRect)contentRect;
-(CGRect)imageRectForContentRect:(CGRect)contentRect;
-(CGRect)editRectForBounds:(CGRect)bounds;
-(CGRect)accessoryRectForBounds:(CGRect)bounds;
-(CGRect)reorderRectForBounds:(CGRect)bounds;
-(void)setFrame:(CGRect)frame;
-(void)setTarget:(id)target;
-(id)target;
-(void)setEditAction:(SEL)action;
-(SEL)editAction;
-(void)setAccessoryAction:(SEL)action;
-(SEL)accessoryAction;
-(void)_setIsAncestorOfFirstResponder:(BOOL)firstResponder;
-(void)removeFromSuperview;
-(void)willMoveToSuperview:(id)superview;
-(void)didMoveToSuperview;
-(void)layoutSubviews;
-(void)willTransitionToState:(unsigned)state;
-(void)didTransitionToState:(unsigned)state;
-(CGRect)contentRectForState:(unsigned)state;
-(void)setBackgroundColor:(id)color;
-(id)backgroundColor;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(int)sectionLocation;
-(void)_setupSelectedBackgroundView;
-(void)setSectionLocation:(int)location;
-(void)setSectionLocation:(int)location animated:(BOOL)animated;
@end

@interface UITableViewCell (UITableViewEditableTextFieldCell)
@property(assign, nonatomic, setter=setTextFieldOffset:) float textFieldOffset;
@property(readonly, retain, nonatomic) UITextField* editableTextField;
-(void)setPlaceHolderValue:(id)value;
-(void)textFieldDidBecomeFirstResponder:(id)textField;
-(void)setReturnAction:(SEL)action;
-(SEL)returnAction;
@end

@interface UITableViewCell (UITableViewCellInternal)
@property(assign, nonatomic) BOOL wasSwiped;
-(id)_tableView;
-(id)_textLabel:(BOOL)label;
-(id)_detailTextLabel:(BOOL)label;
-(id)_editableTextField:(BOOL)field;
-(id)_imageView:(BOOL)view;
-(void)_setShowsReorderControl:(BOOL)control;
-(void)_setEditingStyle:(int)style;
-(void)_setShowingDeleteConfirmation:(BOOL)confirmation;
-(void)_setShouldIndentWhileEditing:(BOOL)_set;
-(void)_setDrawsTopSeparator:(BOOL)separator;
-(void)_drawSeparatorInRect:(CGRect)rect;
-(void)_animateFloatingSeparatorForInsertion:(BOOL)insertion withRowAnimation:(int)rowAnimation;
-(void)_removeFloatingSeparator;
-(id)_removeControl;
-(void)_grabberBeganReorder:(id)reorder;
-(void)_grabberDragged:(id)dragged yDelta:(float)delta;
-(void)_grabberReleased:(id)released;
-(void)_uiRemoveControlMinusButtonHideAnimationDone:(id)done;
-(void)_willBeDeleted;
-(void)removeControl:(id)control willRemoveTarget:(id)target;
-(void)insertControl:(id)control shouldInsertWithTarget:(id)target;
-(void)removeControlWillHideRemoveConfirmation:(id)removeControl;
-(void)editControlWasClicked:(id)clicked;
-(void)deleteConfirmationControlWasClicked:(id)clicked;
-(void)deleteConfirmationControlWasCancelled:(id)cancelled;
-(BOOL)_isReorderable;
-(float)_editingButtonOffset;
-(id)editingData:(BOOL)data;
-(void)removeEditingData;
-(id)_accessoryView:(BOOL)view;
-(id)_editingAccessoryView:(BOOL)view;
-(id)_customAccessoryView:(BOOL)view;
-(id)_customEditingAccessoryView:(BOOL)view;
-(id)_titleForDeleteConfirmationButton;
-(BOOL)_hasAccessoryView;
-(BOOL)_hasEditingAccessoryView;
-(void)_setTarget:(id)target;
-(id)_target;
-(void)_setAccessoryAction:(SEL)action;
-(SEL)_accessoryAction;
-(CGRect)removeControl:(id)control startFrameForTarget:(id)target;
-(CGRect)removeControl:(id)control endFrameForTarget:(id)target;
-(void)removeControl:(id)control wasCanceledForTarget:(id)target;
-(int)tableViewStyle;
-(void)setTableViewStyle:(int)style;
-(id)_scriptingInfo;
-(void)_startToEditTextField;
-(void)_multiselectColorChanged;
@end

@interface UITableViewCell (UITableViewCellStatic)
@property(retain, nonatomic) _UITableViewCellOldEditingData* oldEditingData;
-(void)_createReorderControlIfNeeded;
-(id)_reorderingControl;
-(id)_reorderingSeparatorView;
-(void)_releaseReorderingControl;
-(void)_setGrabberHidden:(BOOL)hidden;
-(void)_finishedFadingGrabber:(id)grabber finished:(BOOL)finished;
-(id)_disclosureImage:(BOOL)image;
-(id)_disclosurePressedImage:(BOOL)image;
-(id)_currentAccessoryView:(BOOL)view;
-(id)_createRemoveControlForStyle:(int)style;
-(void)_releaseRemoveControl;
-(void)_removeRemoveControl;
-(void)_layoutSubviewsAnimated:(BOOL)animated;
-(void)_updateHighlightColorsForView:(id)view highlighted:(BOOL)highlighted;
-(BOOL)_isCurrentlyConsideredHighlighted;
-(void)_updateHighlightColorsForAnimationHalfwayPoint;
-(void)_updateAndCacheBackgroundColorForHighlight;
-(void)_showReorderControl;
-(id)_defaultFont;
-(id)_textLabel;
-(id)_detailTextLabel;
-(id)_editableTextField;
-(id)_imageView;
-(CGSize)_textInsetSize;
-(CGSize)_imageInsetSize;
-(void)_editingTransitionAnimationDidStop:(id)_editingTransitionAnimation finished:(id)finished context:(void*)context;
-(BOOL)longPressGestureCanTransitionToRecognizedState:(id)recognizedState;
-(void)_longPressGestureRecognized:(id)recognized;
-(void)_menuDismissed:(id)dismissed;
-(BOOL)canPerformAction:(SEL)action withSender:(id)sender;
-(void)_performAction:(SEL)action sender:(id)sender;
-(void)cut:(id)cut;
-(void)copy:(id)copy;
-(void)paste:(id)paste;
@end

@interface UITableViewCell (UIKitAccessibilityInterfaceBuilderSupport)
-(BOOL)isElementAccessibilityExposedToInterfaceBuilder;
@end

