/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIGestureRecognizer.h"

@class NSMutableSet, UITouch, UIDelayedAction;

__attribute__((visibility("hidden")))
@interface UITapAndAHalfRecognizer : UIGestureRecognizer {
@private
	CGPoint _startPoint;
	float _allowableMovement;
	int _numberOfFullTaps;
	NSMutableSet* _activeTouches;
	int _currentNumberOfTaps;
	UITouch* _touch;
	UIDelayedAction* _tapTimer;
}
@property(assign, nonatomic) int numberOfFullTaps;
@property(retain, nonatomic) UITouch* touch;
@property(assign, nonatomic) float allowableMovement;
-(id)initWithTarget:(id)target action:(SEL)action;
-(void)dealloc;
-(void)reset;
-(void)clearTapTimer;
-(void)startRecognitionTimer:(double)timer;
-(void)startTapTimer:(double)timer;
-(void)tooSlow:(id)slow;
-(void)recognized:(id)recognized;
-(void)_verifyMovementInAllowableRange;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
@end

