/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIView.h"


__attribute__((visibility("hidden")))
@interface UITableViewCellContentMirror : UIView {
@private
	unsigned _selected : 1;
}
@property(assign, nonatomic, getter=isSelected) BOOL selected;
-(id)initWithFrame:(CGRect)frame;
-(id)cell;
-(void)drawRect:(CGRect)rect;
@end

