/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UITableViewCellLayoutManager.h"


__attribute__((visibility("hidden")))
@interface UITableViewCellLayoutManagerValue1 : UITableViewCellLayoutManager {
}
-(float)defaultTextLabelFontSizeForCell:(id)cell;
-(float)defaultDetailTextLabelFontSizeForCell:(id)cell;
-(id)imageViewForCell:(id)cell;
-(id)textLabelForCell:(id)cell;
-(id)detailTextLabelForCell:(id)cell;
-(void)layoutSubviewsOfCell:(id)cell;
@end

