/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>

@class UIColor;

__attribute__((visibility("hidden")))
@interface UITableViewCellUnhighlightedState : NSObject {
@private
	BOOL _opaque;
	BOOL _highlighted;
	UIColor* _backgroundColor;
}
@property(assign) BOOL opaque;
@property(assign) BOOL highlighted;
@property(retain) UIColor* backgroundColor;
-(void)dealloc;
@end

