/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIWindow.h"

@class NSMutableArray;

@interface UITextEffectsWindow : UIWindow {
	unsigned _activeEffectsCount;
	int _interfaceOrientation;
	NSMutableArray* _touchableSubviews;
}
+(id)sharedTextEffectsWindow;
+(id)sharedTextEffectsWindowAboveStatusBar;
-(BOOL)acceptsGlobalPoint:(CGPoint)point;
-(id)hitTest:(CGPoint)test withEvent:(id)event;
-(id)initWithFrame:(CGRect)frame output:(int)output bitsPerComponent:(int)component;
-(void)dealloc;
-(void)_didRemoveSubview:(id)subview;
-(void)didAddSubview:(id)subview;
-(void)_subviewInteractivityChanged:(id)changed;
-(void)bringSubviewToFront:(id)front;
-(void)sendSubviewToBack:(id)back;
-(void)sortSubviews;
-(void)updateForOrientation:(int)orientation;
-(void)matchDeviceOrientation;
-(BOOL)_isTextEffectsWindow;
@end

