/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "NSObject.h"
#import "UIKit-Structs.h"

@class UIView;
@protocol UITextSelectingContainer;

@protocol UITextMagnifier <NSObject>
@property(readonly, retain, nonatomic) UIView<UITextSelectingContainer>* target;
@property(readonly, assign, nonatomic) CGPoint terminalPoint;
@property(readonly, assign, nonatomic) BOOL terminalPointPlacedCarefully;
@property(assign, nonatomic) CGPoint magnificationPoint;
@property(assign, nonatomic) CGPoint offset;
@property(assign, nonatomic) CGPoint animationPoint;
-(void)beginMagnifyingTarget:(id)target magnificationPoint:(CGPoint)point offset:(CGPoint)offset animated:(BOOL)animated;
-(void)stopMagnifying:(BOOL)magnifying;
-(void)postAutoscrollPoint:(CGPoint)point;
-(void)setAutoscrollDirections:(int)directions;
-(void)autoscrollWillNotStart;
@end

