/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIView.h"


__attribute__((visibility("hidden")))
@interface UITextFieldAtomBackgroundView : UIView {
@private
	int _atomStyle;
}
+(id)_blueAtomBackgroundImage;
+(id)_purpleAtomBackgroundImage;
-(id)initWithFrame:(CGRect)frame;
-(void)drawRect:(CGRect)rect;
-(int)atomStyle;
-(void)setAtomStyle:(int)style;
@end

