/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UITextInputTraits_Private.h"
#import "UIKit-Structs.h"
#import "NSCopying.h"
#import <Foundation/NSObject.h>
#import "NSObject.h"
#import "UITextInputTraits.h"

@class UIColor;

@protocol UITextInputTraits <NSObject>
@optional
@property(assign, nonatomic) int autocapitalizationType;
@property(assign, nonatomic) int autocorrectionType;
@property(assign, nonatomic) int keyboardType;
@property(assign, nonatomic) int keyboardAppearance;
@property(assign, nonatomic) int returnKeyType;
@property(assign, nonatomic) BOOL enablesReturnKeyAutomatically;
@property(assign, nonatomic, getter=isSecureTextEntry) BOOL secureTextEntry;
@end

@interface UITextInputTraits : NSObject <UITextInputTraits, UITextInputTraits_Private, NSCopying> {
	int autocapitalizationType;
	int autocorrectionType;
	int keyboardType;
	int keyboardAppearance;
	int returnKeyType;
	BOOL enablesReturnKeyAutomatically;
	BOOL secureTextEntry;
	CFCharacterSetRef textTrimmingSet;
	UIColor* insertionPointColor;
	unsigned insertionPointWidth;
	int textLoupeVisibility;
	int textSelectionBehavior;
	id textSuggestionDelegate;
	BOOL contentsIsSingleValue;
	BOOL acceptsEmoji;
}
@property(assign, nonatomic) int autocapitalizationType;
@property(assign, nonatomic) int autocorrectionType;
@property(assign, nonatomic) int keyboardType;
@property(assign, nonatomic) int keyboardAppearance;
@property(assign, nonatomic) int returnKeyType;
@property(assign, nonatomic) BOOL enablesReturnKeyAutomatically;
@property(assign, nonatomic, getter=isSecureTextEntry) BOOL secureTextEntry;
@property(assign, nonatomic) CFCharacterSetRef textTrimmingSet;
@property(retain, nonatomic) UIColor* insertionPointColor;
@property(assign, nonatomic) unsigned insertionPointWidth;
@property(assign, nonatomic) int textLoupeVisibility;
@property(assign, nonatomic) int textSelectionBehavior;
@property(assign, nonatomic) id textSuggestionDelegate;
@property(assign, nonatomic) BOOL contentsIsSingleValue;
@property(assign, nonatomic) BOOL acceptsEmoji;
+(id)defaultTextInputTraits;
+(BOOL)keyboardTypeRequiresASCIICapable:(int)capable;
-(void)setToSecureValues;
-(id)dictionaryRepresentation;
-(id)init;
-(void)dealloc;
-(void)setToDefaultValues;
-(void)takeTraitsFrom:(id)from;
-(id)copyWithZone:(NSZone*)zone;
-(id)description;
-(BOOL)isEqual:(id)equal;
@end

