/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "NSObject.h"
#import "UITextInputTraits.h"

@class UIColor;

@protocol UITextInputTraits_Private <NSObject, UITextInputTraits>
@optional
@property(assign, nonatomic) CFCharacterSetRef textTrimmingSet;
@property(retain, nonatomic) UIColor* insertionPointColor;
@property(assign, nonatomic) unsigned insertionPointWidth;
@property(assign, nonatomic) int textLoupeVisibility;
@property(assign, nonatomic) int textSelectionBehavior;
@property(assign, nonatomic) id textSuggestionDelegate;
@property(assign, nonatomic) BOOL contentsIsSingleValue;
@property(assign, nonatomic) BOOL acceptsEmoji;
@required
-(void)takeTraitsFrom:(id)from;
@end

