/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UITextInputTraits.h"
#import "UIKit-Structs.h"
#import "UITextView.h"
#import "UIScrollView.h"

@class UITextInteractionAssistant, UITextSelectionView, UIColor, DOMHTMLElement, NSString, UITouch, UIDelayedAction, UIWebDocumentView, WebFrame, UIFont;
@protocol UITextViewDelegate;

@interface UITextView : UIScrollView <UITextInputTraits> {
@private
	WebFrame* m_frame;
	DOMHTMLElement* m_body;
	int m_marginTop;
	UIDelayedAction* m_selectionTimer;
	UIDelayedAction* m_longPressAction;
	CGPoint m_touchPoint;
	CGPoint m_touchOffset;
	UITouch* m_syntheticTouch;
	BOOL m_editable;
	BOOL m_editing;
	BOOL m_becomesEditableWithGestures;
	BOOL m_selecting;
	BOOL m_handlingMouse;
	BOOL m_sentMouseDown;
	BOOL m_passMouseDownToOther;
	BOOL m_scrollOnMouseUp;
	BOOL m_reentrancyGuard;
	UITextInteractionAssistant* m_interactionAssistant;
	UITextSelectionView* m_selectionView;
	UIWebDocumentView* m_webView;
	UIFont* m_font;
	UIColor* m_textColor;
	int m_textAlignment;
}
@property(assign, nonatomic) int autocapitalizationType;
@property(assign, nonatomic) int autocorrectionType;
@property(assign, nonatomic) int keyboardType;
@property(assign, nonatomic) int keyboardAppearance;
@property(assign, nonatomic) int returnKeyType;
@property(assign, nonatomic) BOOL enablesReturnKeyAutomatically;
@property(assign, nonatomic, getter=isSecureTextEntry) BOOL secureTextEntry;
@property(assign, nonatomic, getter=isEditing) BOOL editing;
@property(assign, nonatomic) id<UITextViewDelegate> delegate;
@property(assign, nonatomic) unsigned dataDetectorTypes;
@property(assign, nonatomic, getter=isEditable) BOOL editable;
@property(assign, nonatomic) NSRange selectedRange;
@property(assign, nonatomic) int textAlignment;
@property(retain, nonatomic) UIColor* textColor;
@property(retain, nonatomic) UIFont* font;
@property(copy, nonatomic) NSString* text;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithFrame:(CGRect)frame webView:(id)view;
-(id)initWithFrame:(CGRect)frame font:(id)font;
-(id)initWithCoder:(id)coder;
-(void)_populateArchivedSubviews:(id)subviews;
-(void)encodeWithCoder:(id)coder;
-(void)commonInitWithWebDocumentView:(id)webDocumentView isDecoding:(BOOL)decoding;
-(void)dealloc;
-(void)removeFromSuperview;
-(void)detachSelectionView;
-(void)detachInteractionAssistant;
-(void)registerForEditingDelegateNotification:(id)editingDelegateNotification selector:(SEL)selector;
-(void)delayedUpdateForKeyboardDidShow;
-(void)keyboardDidShow:(id)keyboard;
-(BOOL)_alwaysHandleScrollerMouseEvent;
-(CGSize)tileSizeForSize:(CGSize)size;
-(id)styleString;
-(void)recalculateStyle;
-(void)didMoveToSuperview;
-(void)updateWebViewObjects;
-(BOOL)becomeFirstResponder;
-(BOOL)resignFirstResponder;
-(BOOL)canBecomeFirstResponder;
-(BOOL)canResignFirstResponder;
-(BOOL)isFirstResponder;
-(void)ensureSelection;
-(CGPoint)constrainedPoint:(CGPoint)point;
-(void)textLoupeTimerAction;
-(CGImageRef)createSnapshotWithRect:(CGRect)rect;
-(id)_syntheticTouch;
-(void)callSuperTouchBegan:(XXStruct_CKAdxD*)began;
-(void)callSuperTouchMoved:(XXStruct_CKAdxD*)moved;
-(void)callSuperTouchEnded:(XXStruct_CKAdxD*)ended;
-(void)touchBegan:(XXStruct_CKAdxD*)began atLocation:(CGPoint)location;
-(void)touchMoved:(XXStruct_CKAdxD*)moved atLocation:(CGPoint)location;
-(void)touchEnded:(XXStruct_CKAdxD*)ended atLocation:(CGPoint)location loupeActive:(BOOL)active loupeTerminalPoint:(CGPoint)point;
-(id)hitTest:(CGPoint)test withEvent:(id)event;
-(id)hitTest:(CGPoint)test forEvent:(GSEventRef)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)mouseDown:(GSEventRef)down;
-(void)mouseDragged:(GSEventRef)dragged;
-(void)mouseUp:(GSEventRef)up;
-(id)content;
-(void)beginSelectionChange;
-(void)endSelectionChange;
-(void)selectionChanged;
-(void)updateSelection;
-(id)selectionView;
-(id)interactionAssistant;
-(CGRect)selectionClipRect;
-(id)selectedText;
-(void)insertText:(id)text;
-(void)selectAll;
-(void)_setRtoLTextDirection:(id)direction;
-(void)_setLtoRTextDirection:(id)direction;
-(BOOL)canPerformAction:(SEL)action withSender:(id)sender;
-(id)undoManagerForWebView:(id)webView;
-(id)undoManager;
-(id)supportedPasteboardTypesForCurrentSelection;
-(id)documentFragmentForPasteboardItemAtIndex:(int)index;
-(void)scrollRectToVisibleInContainingScrollView;
-(void)webViewDidChange:(id)webView;
-(void)performBecomeEditableTasks;
-(void)setFrame:(CGRect)frame;
-(void)setSelectionWithPoint:(CGPoint)point;
-(void)setSelectionToStart;
-(void)setSelectionToEnd;
-(CGRect)rectForSelection:(NSRange)selection;
-(void)scrollSelectionToVisible:(BOOL)visible;
-(void)setContentToHTMLString:(id)htmlstring;
-(id)contentAsHTMLString;
-(id)textInputTraits;
-(void)forwardInvocation:(id)invocation;
-(id)methodSignatureForSelector:(SEL)selector;
-(BOOL)hasText;
-(BOOL)becomesEditableWithGestures;
-(void)setBecomesEditableWithGestures:(BOOL)gestures;
-(int)marginTop;
-(void)setMarginTop:(int)top;
-(CGRect)visibleRect;
-(CGRect)visibleTextRect;
-(id)webView;
-(void)scrollRangeToVisible:(NSRange)visible;
-(BOOL)shouldStartDataDetectors;
-(void)cancelDataDetectorsWithWebLock;
-(void)startDataDetectorsWithWebLock;
-(void)resetDataDetectorsResultsWithWebLock;
-(BOOL)mightHaveLinks;
-(void)tapLinkAtPoint:(CGPoint)point;
-(void)startInteractionWithLinkAtPoint:(CGPoint)point;
-(void)updateInteractionWithLinkAtPoint:(CGPoint)point;
-(void)validateInteractionWithLinkAtPoint:(CGPoint)point;
-(void)cancelInteractionWithLink;
-(void)startLongInteractionWithLinkAtPoint:(CGPoint)point;
-(BOOL)isInteractingWithLink;
-(BOOL)willInteractWithLinkAtPoint:(CGPoint)point;
-(BOOL)keyboardInput:(id)input shouldReplaceTextInRange:(NSRange)range replacementText:(id)text;
-(BOOL)keyboardInput:(id)input shouldInsertText:(id)text isMarkedText:(BOOL)text3;
-(BOOL)keyboardInputShouldDelete:(id)keyboardInput;
-(BOOL)keyboardInputChanged:(id)changed;
-(void)keyboardInputChangedSelection:(id)selection;
-(int)keyboardInput:(id)input positionForAutocorrection:(id)autocorrection;
-(void)webView:(id)view decidePolicyForNavigationAction:(id)navigationAction request:(id)request frame:(id)frame decisionListener:(id)listener;
-(void)setBottomBufferHeight:(float)height;
-(float)bottomBufferHeight;
-(void)setShowScrollerIndicators:(BOOL)indicators;
-(BOOL)showScrollerIndicators;
-(void)displayScrollerIndicators;
-(void)setOffset:(CGPoint)offset;
-(CGPoint)offset;
-(void)setAllowsRubberBanding:(BOOL)banding;
-(void)setScrollingEnabled:(BOOL)enabled;
-(BOOL)scrollingEnabled;
-(void)setAllowsFourWayRubberBanding:(BOOL)banding;
-(void)setScrollerIndicatorSubrect:(CGRect)subrect;
-(void)scrollToMakeCaretVisible:(BOOL)makeCaretVisible;
@end

@interface UITextView (SyntheticEvents)
-(id)_automationValue;
@end

@interface UITextView (UIKitAccessibilityInterfaceBuilderSupport)
-(BOOL)isAccessibilityElementByDefault;
-(BOOL)isElementAccessibilityExposedToInterfaceBuilder;
@end

