/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIButton.h"


__attribute__((visibility("hidden")))
@interface UITexturedButton : UIButton {
}
-(id)initWithFrame:(CGRect)frame;
-(int)buttonType;
-(void)setHighlighted:(BOOL)highlighted;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)drawRect:(CGRect)rect;
-(void)setTitleColor:(id)color forStates:(unsigned)states;
-(id)titleColorForState:(unsigned)state;
-(void)setTitleShadowColor:(id)color forStates:(unsigned)states;
-(id)titleShadowColorForState:(unsigned)state;
-(void)setBackgroundImage:(id)image forStates:(unsigned)states;
-(id)backgroundImageForState:(unsigned)state;
@end

