/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIPushButton.h"


@interface UIThreePartButton : UIPushButton {
	XXStruct_UUz0SD _bkgndSlices;
}
+(id)defaultFont;
-(id)initWithFrame:(CGRect)frame;
-(void)setBackgroundSlices:(XXStruct_UUz0SD)slices;
-(void)setBackgroundImage:(id)image;
-(void)setPressedBackgroundImage:(id)image;
-(id)background;
-(XXStruct_UUz0SD)_backgroundSlices:(CGSize)slices;
-(float)minTitleMargin;
-(void)drawTitleAtPoint:(CGPoint)point width:(float)width;
@end

