/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>

@class DOMNode;

__attribute__((visibility("hidden")))
@interface UIThreadSafeNode : NSObject {
@private
	DOMNode* _node;
}
+(id)threadSafeNodeWithNode:(id)node;
-(id)initWithNode:(id)node;
-(id)description;
-(void)dealloc;
-(BOOL)isKindOfClass:(Class)aClass;
-(BOOL)isEqual:(id)equal;
-(BOOL)respondsToSelector:(SEL)selector;
-(void)forwardInvocation:(id)invocation;
-(id)methodSignatureForSelector:(SEL)selector;
@end

