/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIInternalEvent.h"

@class NSMutableSet;

__attribute__((visibility("hidden")))
@interface UITouchesEvent : UIInternalEvent {
@private
	NSMutableSet* _touches;
	CFDictionaryRef _keyedTouches;
}
-(int)type;
-(id)_init;
-(id)_initWithEvent:(GSEventRef)event touches:(id)touches;
-(id)_initWithTouches:(id)touches keyedTouches:(CFDictionaryRef)touches2;
-(void)dealloc;
-(id)allTouches;
-(id)_allTouches;
-(id)touchesForWindow:(id)window;
-(id)touchesForView:(id)view;
-(id)_touchesForGestureRecognizer:(id)gestureRecognizer;
-(BOOL)_addGestureRecognizersForView:(id)view toTouch:(id)touch;
-(void)_addTouch:(id)touch;
-(void)_clearViewForTouch:(id)touch;
-(void)_removeTouch:(id)touch;
-(void)_removeTouch:(id)touch fromGestureRecognizer:(id)gestureRecognizer;
-(id)_touchesForKey:(id)key;
-(void)_removeTouchesForKey:(id)key;
-(void)_clearTouches;
-(id)_touchesForView:(id)view withPhase:(int)phase;
-(id)_touchesForGesture:(id)gesture withPhase:(int)phase;
-(void)_touchesForGesture:(id)gesture withPhase:(int)phase intoSet:(id)set;
-(id)_windows;
-(id)_gestureRecognizersForWindow:(id)window;
-(id)_sortedGestureRecognizersForWindow:(id)window;
-(id)_viewsForWindow:(id)window;
-(id)_firstTouchForView:(id)view;
-(void)_moveTouchesFromView:(id)view toView:(id)view2;
-(id)_cloneEvent;
-(id)description;
@end

