/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIToolbarButton.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface UIToolbarTextButton : UIToolbarButton {
@private
	NSString* _title;
	NSString* _selectedTitle;
}
-(id)initWithTitle:(id)title selectedTitle:(id)title2 withFont:(id)font withBarStyle:(int)barStyle withStyle:(int)style withTitleWidth:(float)titleWidth possibleTitles:(id)titles withTintColor:(id)tintColor;
-(void)dealloc;
-(void)_setSelected:(BOOL)selected;
-(id)_scriptingInfo;
@end

