/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>
#import "UIKit-Structs.h"


__attribute__((visibility("hidden")))
@interface UITouchTapInfo : NSObject {
@private
	unsigned _tapCount;
	float _multiTapDelay;
	float _rejectAsTapThrehold;
	float _viewTouchPauseThreshold;
	CGPoint _startPosition;
	double _startTime;
}
-(void)releaseAndClearWeakRefs;
-(void)clearTapState;
-(void)touchBegan:(id)began withEvent:(id)event;
-(BOOL)_touchLocationConsideredMovement:(id)movement;
-(void)touchMoved:(id)moved withEvent:(id)event;
-(void)touchEnded:(id)ended withEvent:(id)event;
-(BOOL)cancelTouchTracking;
@end

