/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIToolbarCustomizeView.h"
#import "UIKit-Structs.h"


__attribute__((visibility("hidden")))
@interface UIToolbarCustomizeViewLegacy : UIToolbarCustomizeView {
}
-(id)_fakeEventForEvent:(GSEventRef)event touches:(id)touches;
-(id)_fakeTouchesForEvent:(GSEventRef)event view:(id)view;
-(void)mouseDown:(GSEventRef)down;
-(void)mouseDragged:(GSEventRef)dragged;
-(void)mouseUp:(GSEventRef)up;
-(void)buttonBarMouseDown:(GSEventRef)down;
-(void)buttonBarMouseDragged:(GSEventRef)dragged;
-(void)buttonBarMouseUp:(GSEventRef)up;
@end

