/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import <Foundation/NSObject.h>
#import "UITouch.h"

@class NSMutableArray, UIView, UIWindow;

@interface UITouch : NSObject {
	double _timestamp;
	int _phase;
	int _savedPhase;
	unsigned _tapCount;
	UIWindow* _window;
	UIView* _view;
	UIView* _gestureView;
	NSMutableArray* _gestureRecognizers;
	CGPoint _locationInWindow;
	CGPoint _previousLocationInWindow;
	struct {
		unsigned _firstTouchForView : 1;
		unsigned _isTap : 1;
		unsigned _isWarped : 1;
		unsigned _isDelayed : 1;
		unsigned _sentTouchesEnded : 1;
	} _touchFlags;
}
@property(readonly, retain, nonatomic) UIView* view;
@property(readonly, retain, nonatomic) UIWindow* window;
@property(readonly, assign, nonatomic) unsigned tapCount;
@property(readonly, assign, nonatomic) int phase;
@property(readonly, assign, nonatomic) double timestamp;
-(void)dealloc;
-(int)info;
-(BOOL)isTap;
-(BOOL)isWarped;
-(void)setIsDelayed:(BOOL)delayed;
-(BOOL)isDelayed;
-(void)setSentTouchesEnded:(BOOL)ended;
-(BOOL)sentTouchesEnded;
-(id)gestureRecognizers;
-(CGPoint)locationInView:(id)view;
-(CGPoint)previousLocationInView:(id)view;
-(void)_loadStateFromTouch:(id)touch;
@end

@interface UITouch (UITouchInternal)
@property(retain, nonatomic) UIView* gestureView;
@property(retain, nonatomic) UIView* view;
@property(retain, nonatomic) UIWindow* window;
@property(assign, nonatomic) BOOL sentTouchesEnded;
@property(assign, nonatomic) BOOL isWarped;
@property(assign, nonatomic) BOOL isTap;
@property(assign, nonatomic) unsigned tapCount;
@property(assign, nonatomic) int phase;
@property(assign, nonatomic) double timestamp;
+(id)_createTouchesWithGSEvent:(GSEventRef)gsevent phase:(int)phase view:(id)view;
-(void)_setIsFirstTouchForView:(BOOL)view;
-(BOOL)_isFirstTouchForView;
-(void)_setLocationInWindow:(CGPoint)window resetPrevious:(BOOL)previous;
-(id)description;
-(void)_addGestureRecognizer:(id)recognizer;
-(void)_removeGestureRecognizer:(id)recognizer;
-(id)_gestureRecognizers;
-(void)_clearGestureRecognizers;
-(BOOL)_touchesBeganWasDelayed;
-(void)_pushPhase:(int)phase;
-(void)_popPhase;
-(CGPoint)_locationInWindow:(id)window;
@end

