/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>
#import "UIKit-Structs.h"

@class UITouch;

__attribute__((visibility("hidden")))
@interface UITouchData : NSObject {
@private
	CGPoint startTouchDownLocation;
	unsigned lastTapCount;
	double lastTouchUpTimestamp;
	double lastTouchDownTimestamp;
	BOOL touchIsValidTap;
	UITouch* lastTouch;
}
@end

