/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "NSCoding.h"
#import "UIView.h"


@interface UITransitionView : UIView <NSCoding> {
	UIView* _fromView;
	UIView* _toView;
	UIResponder* _firstResponderToRemember;
	id _delegate;
	struct {
		unsigned shouldSendTouchPauseUp : 1;
		unsigned delegateViewHandleTapWithCountEvent : 1;
		unsigned delegateViewHandleTapWithCountEventFingerCount : 1;
		unsigned delegateViewHandleTouchPauseIsDown : 1;
		unsigned reserved : 28;
	} _transitionViewFlags;
}
@property(assign, nonatomic) BOOL shouldNotifyDidCompleteImmediately;
+(double)defaultDurationForTransition:(int)transition;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)dealloc;
-(double)durationForTransition:(int)transition;
-(void)_didStartTransition;
-(void)_didCompleteTransition:(BOOL)transition;
-(BOOL)transition:(int)transition toView:(id)view;
-(void)notifyDidCompleteTransition:(id)notify;
-(BOOL)transition:(int)transition fromView:(id)view toView:(id)view3;
-(id)fromView;
-(id)toView;
-(BOOL)isTransitioning;
-(void)setDelegate:(id)delegate;
-(id)delegate;
-(BOOL)ignoresInteractionEvents;
-(void)setIgnoresInteractionEvents:(BOOL)events;
-(void)_startTransition:(int)transition withDuration:(float)duration;
-(void)_transitionDidStop:(id)_transition finished:(id)finished;
@end

