/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIAnimation.h"
#import "UIKit-Structs.h"


@interface UITransformAnimation : UIAnimation {
	CGAffineTransform _startTransform;
	CGAffineTransform _endTransform;
}
-(void)setStartTransform:(CGAffineTransform)transform;
-(void)setEndTransform:(CGAffineTransform)transform;
-(CGAffineTransform)_transformWithMultiplier:(float)multiplier;
-(void)setProgress:(float)progress;
-(CGAffineTransform)transformForFraction:(float)fraction;
@end

