/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>

@class NSIndexPath;

__attribute__((visibility("hidden")))
@interface UIUpdateItem : NSObject {
@private
	int _action;
	NSIndexPath* _indexPath;
	int _animation;
	float _offset;
}
@property(readonly, assign, nonatomic) int action;
@property(readonly, assign, nonatomic) NSIndexPath* indexPath;
@property(readonly, assign, nonatomic) int animation;
@property(assign, nonatomic) float offset;
-(id)initWithAction:(int)action forIndexPath:(id)indexPath animation:(int)animation;
-(void)dealloc;
-(id)_actionDescription;
-(BOOL)isSectionOperation;
-(int)compareIndexPaths:(id)paths;
-(int)inverseCompareIndexPaths:(id)paths;
@end

