/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UINavigationController.h"

@class NSMutableDictionary, NSString;
@protocol UINavigationControllerDelegate, UIVideoEditorControllerDelegate;

@interface UIVideoEditorController : UINavigationController {
@private
	int _previousStatusBarMode;
	NSMutableDictionary* _properties;
	struct {
		unsigned visible : 1;
		unsigned isCleaningUp : 1;
		unsigned didRevertStatusBar : 1;
	} _flags;
}
@property(assign, nonatomic) id<UINavigationControllerDelegate, UIVideoEditorControllerDelegate> delegate;
@property(assign, nonatomic) unsigned videoQuality;
@property(assign, nonatomic) double videoMaximumDuration;
@property(copy, nonatomic) NSString* videoPath;
+(BOOL)canEditVideoAtPath:(id)path;
-(id)init;
-(void)setParentViewController:(id)controller;
-(void)viewWillAppear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidDisappear:(BOOL)view;
-(BOOL)_didRevertStatusBar;
-(BOOL)_isSupportedInterfaceOrientation:(int)orientation;
-(void)_removeAllChildren;
-(id)_createInitialController;
-(void)_setupControllers;
-(void)_autoDismiss;
-(void)editVideoViewControllerDidCancel:(id)editVideoViewController;
-(void)editVideoViewController:(id)controller didTrimVideoWithOptions:(id)options;
-(void)editVideoViewController:(id)controller didFailWithError:(id)error;
-(void)_setProperties:(id)properties;
-(void)_initializeProperties;
-(id)_properties;
-(void)_setValue:(id)value forProperty:(id)property;
-(id)_valueForProperty:(id)property;
@end

