/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import <Foundation/NSObject.h>

@class UIView;

__attribute__((visibility("hidden")))
@interface UIViewHeartbeat : NSObject {
@private
	UIView* _view;
	SEL _selector;
	GSHeartbeatRef _heartbeat;
}
+(void)startHeartbeatWithView:(id)view selector:(SEL)selector inRunLoopMode:(id)runLoopMode;
+(void)stopHeartbeatWithView:(id)view selector:(SEL)selector;
-(void)dealloc;
@end

