/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface UIWebSelectionGraph : NSObject {
@private
	NSMutableArray* _selectionNodes;
}
-(id)init;
-(void)dealloc;
-(void)clearNodes;
-(id)addNodeFromSelection:(id)selection;
-(void)exploreFromNode:(id)node outwards:(BOOL)outwards maxDepth:(int)depth;
-(void)exploreFromNode:(id)node;
@end

