/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIView.h"
#import "UIKit-Structs.h"

@class UIWebDragDotView, NSArray, NSMutableArray;
@protocol UITextSelectingContainer, UIWebTextRangeViewController;

__attribute__((visibility("hidden")))
@interface UIWebTextRangeView : UIView {
@private
	UIView<UITextSelectingContainer>* m_container;
	NSArray* _rects;
	NSMutableArray* _rectViews;
	UIWebDragDotView* _topDot;
	UIWebDragDotView* _bottomDot;
	BOOL _magnifying;
	id<UIWebTextRangeViewController> _controller;
}
@property(copy, nonatomic) NSArray* rects;
@property(assign, nonatomic) id<UIWebTextRangeViewController> controller;
@property(readonly, assign, nonatomic) UIView<UITextSelectingContainer>* container;
-(id)initWithFrame:(CGRect)frame textContainer:(id)container;
-(void)dealloc;
-(void)removeFromSuperview;
-(CGRect)rectAtIndex:(int)index;
-(id)rectViewAtIndex:(int)index;
-(CGRect)boundingRect;
-(void)updateDragDots;
-(void)updateRectViews;
-(CGRect)startEdge;
-(CGRect)endEdge;
-(CGPoint)startCorner;
-(CGPoint)endCorner;
-(id)hitTest:(CGPoint)test withEvent:(id)event;
-(void)prepareForMagnification;
-(void)doneMagnifying;
-(void)geometryChanged;
@end

