/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>

@class UIWebSelectionGraph, UIWebSelection;

__attribute__((visibility("hidden")))
@interface UIWebSelectionNode : NSObject {
@private
	UIWebSelectionNode* _fromTopByExpanding;
	UIWebSelectionNode* _fromTopByContracting;
	UIWebSelectionNode* _fromBottomByExpanding;
	UIWebSelectionNode* _fromBottomByContracting;
	UIWebSelectionNode* _fromRightByExpanding;
	UIWebSelectionNode* _fromRightByContracting;
	UIWebSelectionNode* _fromLeftByExpanding;
	UIWebSelectionNode* _fromLeftByContracting;
	UIWebSelectionGraph* _sharedGraph;
	UIWebSelection* _selection;
	BOOL _invalid;
}
@property(retain) UIWebSelection* selection;
-(id)initWithSelection:(id)selection inGraph:(id)graph;
-(void)dealloc;
-(id*)nodeByReferenceFromEdge:(int)edge outwards:(BOOL)outwards;
-(int)oppositeEdge:(int)edge;
-(id)nodeByMovingEdge:(int)edge outwards:(BOOL)outwards;
-(void)invalidate;
@end

