/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIView.h"

@class UIHighlightView, UILabel;

__attribute__((visibility("hidden")))
@interface UIWebViewLabel : UIView {
@private
	UILabel* _label;
	UIHighlightView* _highlight;
}
-(id)initWithFrame:(CGRect)frame;
-(void)sizeToFit;
-(void)setText:(id)text;
-(void)dealloc;
@end

