/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UILongPressGestureRecognizer.h"

@class UIWebDocumentView;

__attribute__((visibility("hidden")))
@interface UIWebLongPressInSelectableRecognizer : UILongPressGestureRecognizer {
@private
	UIWebDocumentView* _documentView;
}
@property(assign, nonatomic) UIWebDocumentView* documentView;
-(void)setState:(int)state;
@end

