/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>

@class NSDictionary, NSMutableDictionary, NSMutableArray;

@interface UIWebFormPasswordsEditor : NSObject {
	NSDictionary* _credentialsByProtectionSpace;
	NSMutableArray* _flattenedCredentials;
	NSMutableDictionary* _credentialToProtectionSpaceMap;
	BOOL _ignoreNotifications;
}
+(id)sharedPasswordsEditor;
-(id)protectionSpaceForCredential:(id)credential;
-(id)addressStringForCredential:(id)credential;
-(void)resetCredentials;
-(void)credentialsChanged:(id)changed;
-(void)startMonitoringCredentials;
-(void)stopMonitoringCredentials;
-(void)dealloc;
-(void)removeSelectedItems:(id)items;
-(void)removeAll;
@end

