/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIView.h"
#import "UIKit-Structs.h"
#import "UIWindow.h"

@class NSUndoManager;

@interface UIWindow : UIView {
@private
	id _delegate;
	float _windowLevel;
	id _layerContext;
	UIView* _lastMouseDownView;
	UIView* _lastMouseEnteredView;
	UIResponder* _firstResponder;
	id _fingerInfo;
	id _touchData;
	int _viewOrientation;
	UIView* _exclusiveTouchView;
	NSUndoManager* _undoManager;
	struct {
		unsigned delegateWillRotate : 1;
		unsigned delegateDidRotate : 1;
		unsigned delegateWillAnimateFirstHalf : 1;
		unsigned delegateDidAnimationFirstHalf : 1;
		unsigned delegateWillAnimateSecondHalf : 1;
		unsigned autorotatesToPortrait : 1;
		unsigned autorotatesToPortraitUpsideDown : 1;
		unsigned autorotatesToLandscapeLeft : 1;
		unsigned autorotatesToLandscapeRight : 1;
		unsigned dontBecomeKeyOnOrderFront : 1;
		unsigned output : 1;
		unsigned inGesture : 1;
		unsigned trackingStatusBar : 1;
		unsigned cancelScroller : 1;
		unsigned bitsPerComponent : 4;
		unsigned autorotates : 1;
		unsigned isRotating : 1;
		unsigned isUsingOnePartRotationAnimation : 1;
		unsigned isHandlingContentRotation : 1;
		unsigned disableAutorotationCount : 4;
		unsigned needsAutorotationWhenReenabled : 1;
		unsigned forceTwoPartRotationAnimation : 1;
		unsigned orderKeyboardInAfterRotating : 1;
	} _windowFlags;
	id _windowController;
}
@property(readonly, assign, nonatomic, getter=isKeyWindow) BOOL keyWindow;
@property(assign, nonatomic) float windowLevel;
+(CGRect)constrainFrameToScreen:(CGRect)screen;
+(id)keyWindow;
+(void)_noteStatusBarHeightChanged:(float)changed oldHeight:(float)height fence:(int)fence;
+(id)_ioSurfacePropertyDictionaryForRect:(CGRect)rect;
+(void*)createIOSurfaceWithContextId:(unsigned)contextId frame:(CGRect)frame;
+(void*)createIOSurfaceWithContextIds:(const unsigned*)contextIds count:(unsigned)count frame:(CGRect)frame;
+(void*)createScreenIOSurface;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithFrame:(CGRect)frame output:(int)output;
-(void)_commonInit;
-(id)initWithFrame:(CGRect)frame output:(int)output bitsPerComponent:(int)component;
-(id)initWithContentRect:(CGRect)contentRect;
-(id)initWithCoder:(id)coder;
-(void)dealloc;
-(void)setContentView:(id)view;
-(id)representation;
-(void)_createWindow;
-(BOOL)_ignoresHitTest;
-(BOOL)_disableGroupOpacity;
-(BOOL)_disableEdgeAntialiasing;
-(unsigned)_contextId;
-(void)makeKeyAndOrderFront:(id)front;
-(void)orderFront:(id)front;
-(void)_orderFrontWithoutMakingKey;
-(void)orderOut:(id)anOut;
-(void)setHidden:(BOOL)hidden;
-(void)makeKey:(id)key;
-(CGPoint)warpPoint:(CGPoint)point;
-(BOOL)_pointInStatusBar:(CGPoint)statusBar;
-(void)_handleMouseDown:(GSEventRef)down;
-(void)_handleMouseDragged:(GSEventRef)dragged;
-(void)_handleMouseUp:(GSEventRef)up;
-(void)_handleMouseEntered:(GSEventRef)entered;
-(void)_handleMouseMoved:(GSEventRef)moved;
-(void)_handleMouseExited:(GSEventRef)exited;
-(BOOL)_isScrollingEnabledForView:(id)view;
-(void)_statusBarMouseDown:(GSEventRef)down;
-(void)_statusBarMouseDragged:(GSEventRef)dragged;
-(void)_statusBarMouseUp:(GSEventRef)up;
-(void)_sendGesturesForEvent:(id)event;
-(void)_sendTouchesForEvent:(id)event;
-(void)sendEvent:(id)event;
-(CGPoint)convertPoint:(CGPoint)point toWindow:(id)window;
-(CGPoint)convertPoint:(CGPoint)point fromWindow:(id)window;
-(CGRect)convertRect:(CGRect)rect toWindow:(id)window;
-(CGRect)convertRect:(CGRect)rect fromWindow:(id)window;
-(void)_setExclusiveTouchView:(id)view;
-(id)_exclusiveTouchView;
-(void)_beginModalSession;
-(void)_endModalSession;
-(id)nextResponder;
-(BOOL)_containedInAbsoluteResponderChain;
-(CGPoint)convertWindowToDevice:(CGPoint)device;
-(CGPoint)convertDeviceToWindow:(CGPoint)window;
-(void)setLevel:(float)level;
-(float)level;
-(void)setBecomeKeyOnOrderFront:(BOOL)front;
-(void)_slideHeaderView:(id)view andFooterView:(id)view2 offScreen:(BOOL)screen forInterfaceOrientation:(int)interfaceOrientation;
-(void)_positionHeaderView:(id)view andFooterView:(id)view2 outsideContentViewForInterfaceOrientation:(int)interfaceOrientation;
-(void)_clearPendingKeyboardChanges;
-(BOOL)_shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)_handleStatusBarOrientationChange:(id)change;
-(void)_handleDeviceOrientationChange:(id)change;
-(void)_applicationDidBeginIgnoringInteractionEvents:(id)_application;
-(void)_applicationDidEndIgnoringInteractionEvents:(id)_application;
-(void)_updateToInterfaceOrientation:(int)interfaceOrientation animated:(BOOL)animated;
-(void)_updateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration force:(BOOL)force;
-(void)_updateInterfaceOrientationFromDeviceOrientation;
-(void)beginDisablingInterfaceAutorotation;
-(BOOL)isInterfaceAutorotationDisabled;
-(void)endDisablingInterfaceAutorotation;
-(void)setAutorotates:(BOOL)autorotates;
-(void)setAutorotates:(BOOL)autorotates forceUpdateInterfaceOrientation:(BOOL)orientation;
-(void)_setRotatableViewOrientation:(int)orientation duration:(double)duration;
-(int)_degreesToRotateFromInterfaceOrientation:(int)interfaceOrientation toInterfaceOrientation:(int)interfaceOrientation2;
-(void)_forceTwoPartRotationAnimation:(BOOL)animation;
-(void)_updateStatusBarToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration fenceID:(int)anId animation:(int)animation;
-(void)_updateStatusBarToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)_setRotatableViewOrientation:(int)orientation duration:(double)duration force:(BOOL)force;
-(void)_finishedFirstHalfRotation:(id)rotation finished:(id)finished context:(void*)context;
-(void)_finishedFullRotation:(id)rotation finished:(id)finished context:(void*)context;
-(BOOL)autorotates;
-(BOOL)isRotating;
-(BOOL)isUsingOnePartRotationAnimation;
-(BOOL)isHandlingContentRotation;
-(int)interfaceOrientation;
-(void)synchronizeDrawingWithID:(int)anId;
-(void)synchronizeDrawingWithID:(int)anId count:(unsigned)count;
-(void)handleStatusBarChangeFromHeight:(float)height toHeight:(float)height2;
-(int)windowOutput;
-(int)bitsPerComponent;
-(void)setDelegate:(id)delegate;
-(id)delegate;
-(void)makeKeyWindow;
-(void)becomeKeyWindow;
-(void)resignKeyWindow;
-(void)makeKeyAndVisible;
-(id)contentView;
-(void)_registerChargedView:(id)view;
-(void)_unregisterChargedView:(id)view;
-(void)_registerSwipeView:(id)view;
-(void)_unregisterSwipeView:(id)view;
-(void)_registerScrollToTopView:(id)topView;
-(void)_unregisterScrollToTopView:(id)topView;
-(void)_setFirstResponder:(id)responder;
-(id)firstResponder;
-(id)_firstResponder;
-(BOOL)_becomeFirstResponderWhenPossible;
-(id)undoManager;
-(void)undo:(id)undo;
-(void)redo:(id)redo;
-(BOOL)canPerformAction:(SEL)action withSender:(id)sender;
-(void)_setMouseDownView:(id)view withEvent:(GSEventRef)event;
-(void)_setMouseEnteredView:(id)view;
-(BOOL)_clearMouseView;
-(BOOL)_allowsContextHosting;
-(void*)createIOSurfaceWithFrame:(CGRect)frame;
-(void*)createIOSurface;
-(void)_setCancelScroller:(BOOL)scroller;
-(BOOL)acceptsGlobalPoint:(CGPoint)point;
-(BOOL)_isLayerHidden;
-(void)_setLayerHidden:(BOOL)hidden;
-(id)_touchData;
@end

@interface UIWindow (UITextEffectsWindowAdditions)
-(BOOL)_isTextEffectsWindow;
@end

@interface UIWindow (UITextEffectsWindow)
-(void)updateForOrientation:(int)orientation;
-(void)matchDeviceOrientation;
@end

@interface UIWindow (UIKitAccessibilityInterfaceBuilderSupport)
-(BOOL)isElementAccessibilityExposedToInterfaceBuilder;
@end

