/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <WebKit/WebHTMLRepresentation.h>


@interface WebHTMLRepresentation (CreditCardAutoFillExtras)
-(BOOL)formElementLooksLikeCreditCardNumberField:(id)field;
-(BOOL)formElementLooksLikeSecurityCodeField:(id)field;
@end

